/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DllInjector {
  constructor(injectorLibPath: string)
  unload(): void
  startProcess(exePath: string, workDir?: string | undefined | null, startArgs?: string | undefined | null): void
  openProcess(startMethod: string, exePath?: string | undefined | null, workDir?: string | undefined | null, startArgs?: Array<string> | undefined | null, processFlags?: number | undefined | null, processName?: string | undefined | null, dllPaths?: Array<string> | undefined | null, cmd?: string | undefined | null, injectTimeout?: number | undefined | null): Promise<unknown>
  hookLibrary(dllPath: string, targetProcess: string): void
  waitForInjection(timeout?: number | undefined | null): Promise<unknown>
  unhookLibrary(): boolean
  injectLibraries(dllPaths: Array<string>, processName?: string | undefined | null, pid?: number | undefined | null, timeout?: number | undefined | null): Promise<unknown>
}
export declare class Injector {
  static attach(pid: number): Injector
  /** DLL을 주입합니다. 로드된 모듈 핸들을 반환합니다. */
  inject(path: string): number
  /** 주입된 DLL을 언로드합니다. */
  uninject(handle: number): void
  /** 명시적으로 리소스를 해제합니다. (GC를 기다리지 않음) */
  detach(): void
}
