package mod

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type namespaceMergeSource struct {
	iniPath string
	index   int
}

type namespaceWrapSource struct {
	iniPath string
	text    string
}

type namespaceMergeOptions struct {
	masterDir          string
	name               string
	sources            []namespaceMergeSource
	forwardKey         string
	backKey            string
	includeVanilla     bool
	existingMasterPath string
	created            *[]mergeRollback
}

func writeNamespaceMerge(options namespaceMergeOptions) (string, error) {
	created := options.created
	if created == nil {
		empty := []mergeRollback{}
		created = &empty
	}
	wrapSources := make([]namespaceWrapSource, 0, len(options.sources))
	for _, source := range options.sources {
		if err := ensureMergeBackup(source.iniPath, created); err != nil {
			return "", err
		}
		raw, err := os.ReadFile(source.iniPath)
		if err != nil {
			return "", err
		}
		unwrapped, err := unwrapNamespace(string(raw))
		if err != nil {
			return "", err
		}
		wrapped := wrapNamespaceHashes(unwrapped, options.name, source.index)
		if err := recordMergeWrite(source.iniPath, created); err != nil {
			return "", err
		}
		if err := os.WriteFile(source.iniPath, []byte(wrapped), 0o644); err != nil {
			return "", err
		}
		wrapSources = append(wrapSources, namespaceWrapSource{iniPath: source.iniPath, text: wrapped})
	}

	representative := pickNamespaceRepresentative(wrapSources)
	representativeText := ""
	if representative != nil {
		representativeText = representative.text
	}
	positionHash := ""
	var positionMatchLines []string
	if representative != nil {
		positionHash = extractPositionHash(representativeText)
		positionMatchLines = extractPositionSectionMatchLines(representativeText)
	}
	dialect := "unknown"
	if representativeText != "" {
		dialect = detectMergeDialect(representativeText)
	}
	representativeSectionName := "TextureOverride" + options.name + "Position"
	switch dialect {
	case "wwmi":
		representativeSectionName = "TextureOverride" + options.name + "MarkBoneDataCB"
	case "efmi":
		representativeSectionName = "TextureOverride" + options.name + "Component0"
	}

	maxSwapIndex := 0
	for _, source := range options.sources {
		if source.index > maxSwapIndex {
			maxSwapIndex = source.index
		}
	}
	cycle := make([]string, maxSwapIndex+1)
	for i := range cycle {
		cycle[i] = fmt.Sprint(i)
	}

	existingDir := options.masterDir
	if options.existingMasterPath != "" {
		existingDir = filepath.Dir(options.existingMasterPath)
	}
	var existingListed []string
	if options.existingMasterPath != "" {
		raw, err := os.ReadFile(options.existingMasterPath)
		if err != nil {
			return "", err
		}
		for _, entry := range extractMergedModPaths(string(raw)) {
			existingListed = append(existingListed, resolveAgainst(existingDir, entry))
		}
	}
	currentSources := make([]string, 0, len(wrapSources))
	for _, entry := range wrapSources {
		currentSources = append(currentSources, resolveAgainst(options.masterDir, entry.iniPath))
	}
	uniqueListed := uniqueMergePaths(append(existingListed, currentSources...))

	master := []string{
		formatMergedModHeader(options.masterDir, uniqueListed),
		fmt.Sprintf("namespace = %s\\Master", options.name),
		"; Constants ---------------------------",
		"",
		"[Constants]",
		"global persist $swapvar = 0",
		"global $active",
		"global $creditinfo = 0",
		"",
		"[KeySwap]",
		"condition = $active == 1",
		fmt.Sprintf("key = %s", options.forwardKey),
		fmt.Sprintf("back = %s", options.backKey),
		"type = cycle",
		fmt.Sprintf("$swapvar = %s", strings.Join(cycle, ",")),
		"$creditinfo = 0",
		"",
		"[Present]",
		"post $active = 0",
		"",
		"; Overrides ---------------------------",
		"",
	}
	if positionHash != "" {
		master = append(master,
			"["+representativeSectionName+"]",
			"hash = "+positionHash,
		)
		master = append(master, positionMatchLines...)
		master = append(master, "$active = 1", "")
	}
	master = append(master, "; .ini generated by Nahida Desktop namespace merger", "")
	masterPath := filepath.Join(options.masterDir, "Master"+options.name+".ini")
	if err := recordMergeWrite(masterPath, created); err != nil {
		return "", err
	}
	if err := os.WriteFile(masterPath, []byte(strings.Join(master, "\n")), 0o644); err != nil {
		return "", err
	}
	return masterPath, nil
}

func pickNamespaceRepresentative(sources []namespaceWrapSource) *namespaceWrapSource {
	pick := func(pred func(namespaceWrapSource) bool) *namespaceWrapSource {
		for i := range sources {
			if pred(sources[i]) {
				return &sources[i]
			}
		}
		return nil
	}
	if found := pick(func(entry namespaceWrapSource) bool {
		return !isHelperIniName(filepath.Base(entry.iniPath)) && extractPositionSectionHash(entry.text) != ""
	}); found != nil {
		return found
	}
	if found := pick(func(entry namespaceWrapSource) bool {
		return !isHelperIniName(filepath.Base(entry.iniPath)) && extractPositionHash(entry.text) != ""
	}); found != nil {
		return found
	}
	if found := pick(func(entry namespaceWrapSource) bool {
		return !isHelperIniName(filepath.Base(entry.iniPath))
	}); found != nil {
		return found
	}
	if found := pick(func(entry namespaceWrapSource) bool {
		return extractPositionSectionHash(entry.text) != ""
	}); found != nil {
		return found
	}
	if len(sources) == 0 {
		return nil
	}
	return &sources[0]
}

func collectNamespaceChildren(masterPath string) ([]string, error) {
	masterDir := filepath.Dir(masterPath)
	raw, err := os.ReadFile(masterPath)
	if err != nil {
		return nil, err
	}
	text := string(raw)
	namespace := extractMergeNamespace(text)
	var listed []string
	for _, entry := range extractMergedModPaths(text) {
		candidate := resolveAgainst(masterDir, entry)
		if _, readErr := os.ReadFile(candidate); readErr != nil {
			continue
		}
		listed = append(listed, candidate)
	}

	token := regexp.MustCompile(`(?i)\\Master$`).ReplaceAllString(namespace, "")
	var pattern *regexp.Regexp
	if token != "" {
		pattern = regexp.MustCompile(`(?i)\$\\` + regexp.QuoteMeta(token) + `\\Master\\swapvar`)
	} else {
		pattern = regexp.MustCompile(`(?i)\$\\[^\\\s]+\\Master\\swapvar`)
	}

	masterAbs := resolveAgainst("", masterPath)
	var scanned []string
	err = filepath.WalkDir(masterDir, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.Type().IsRegular() || !strings.EqualFold(filepath.Ext(entry.Name()), ".ini") {
			return nil
		}
		if resolveAgainst("", path) == masterAbs {
			return nil
		}
		fileName := entry.Name()
		if isFileDisabledIniName(fileName) || isBackupIniName(fileName) {
			return nil
		}
		child, readErr := os.ReadFile(path)
		if readErr == nil {
			content := string(child)
			if pattern.MatchString(content) || hasMasterSwapRef(content) {
				scanned = append(scanned, resolveAgainst("", path))
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return uniqueMergePaths(append(listed, scanned...)), nil
}

func unwrapNamespace(text string) (string, error) {
	parsed := parseMergeINI(text)
	for i := range parsed.sections {
		parsed.sections[i].lines = unwrapSectionLines(parsed.sections[i].lines)
	}
	next := serializeMergeINI(parsed)
	if hasCompoundMasterSwap(text) || hasMasterSwapRef(next) {
		return "", errors.New("NAMESPACE_UNWRAP_INCOMPLETE")
	}
	return next, nil
}

func unwrapSectionLines(lines []mergeINILine) []mergeINILine {
	nextLines := make([]mergeINILine, 0, len(lines))
	masterSwapActive := false
	innerIfDepth := 0
	for index, line := range lines {
		trimmed := strings.TrimSpace(line.raw)
		lower := strings.ToLower(trimmed)
		if !masterSwapActive && innerIfDepth == 0 &&
			line.kind == mergeINIKV && strings.EqualFold(line.key, "match_priority") &&
			precedesMasterSwapIf(lines, index) {
			continue
		}
		if masterSwapIfRE.MatchString(trimmed) {
			if !masterSwapActive {
				masterSwapActive = true
				innerIfDepth = 0
				continue
			}
			innerIfDepth++
			nextLines = append(nextLines, unindentMergeINILine(line))
			continue
		}
		if masterSwapActive && innerIfDepth == 0 &&
			(masterSwapElseIfRE.MatchString(trimmed) || masterSwapElseRE.MatchString(trimmed)) {
			continue
		}
		if strings.HasPrefix(lower, "if ") || strings.HasPrefix(lower, "if\t") {
			if masterSwapActive {
				innerIfDepth++
				nextLines = append(nextLines, unindentMergeINILine(line))
			} else {
				nextLines = append(nextLines, line)
			}
			continue
		}
		if lower == "endif" {
			if masterSwapActive {
				if innerIfDepth > 0 {
					innerIfDepth--
					nextLines = append(nextLines, unindentMergeINILine(line))
				} else {
					masterSwapActive = false
				}
			} else {
				nextLines = append(nextLines, line)
			}
			continue
		}
		if masterSwapActive {
			nextLines = append(nextLines, unindentMergeINILine(line))
		} else {
			nextLines = append(nextLines, line)
		}
	}
	return nextLines
}

func precedesMasterSwapIf(lines []mergeINILine, index int) bool {
	for _, entry := range lines[index+1:] {
		if strings.TrimSpace(entry.raw) == "" {
			continue
		}
		if entry.kind == mergeINIKV && isOverrideMatchKey(entry.key) {
			continue
		}
		return masterSwapIfRE.MatchString(strings.TrimSpace(entry.raw))
	}
	return false
}

func unindentMergeINILine(line mergeINILine) mergeINILine {
	if line.kind == mergeINIKV || line.kind == mergeINIOther || line.kind == mergeINIComment {
		unindented := line.raw
		switch {
		case strings.HasPrefix(unindented, "\t"):
			unindented = unindented[1:]
		case strings.HasPrefix(unindented, "    "):
			unindented = unindented[4:]
		case strings.HasPrefix(unindented, "   "):
			unindented = unindented[3:]
		case strings.HasPrefix(unindented, "  "):
			unindented = unindented[2:]
		case strings.HasPrefix(unindented, " "):
			unindented = unindented[1:]
		}
		return classifyMergeINILine(unindented)
	}
	return line
}

func formatMergedModHeader(baseDir string, iniPaths []string) string {
	rels := make([]string, 0, len(iniPaths))
	for _, iniPath := range iniPaths {
		rels = append(rels, mergeRelativePath(baseDir, iniPath))
	}
	return "; Merged Mod: " + strings.Join(rels, ", ")
}

func uniqueMergePaths(paths []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(paths))
	for _, path := range paths {
		if path == "" {
			continue
		}
		if _, ok := seen[path]; ok {
			continue
		}
		seen[path] = struct{}{}
		out = append(out, path)
	}
	return out
}

func resolveAgainst(base, entry string) string {
	cleaned := filepath.FromSlash(strings.TrimSpace(entry))
	var resolved string
	if filepath.IsAbs(cleaned) || base == "" {
		resolved = cleaned
		if !filepath.IsAbs(resolved) {
			if abs, err := filepath.Abs(resolved); err == nil {
				resolved = abs
			}
		} else if abs, err := filepath.Abs(resolved); err == nil {
			resolved = abs
		}
		return resolved
	}
	if abs, err := filepath.Abs(filepath.Join(base, cleaned)); err == nil {
		return abs
	}
	return filepath.Join(base, cleaned)
}

func sanitizeMergeToken(name string) (string, error) {
	token := regexp.MustCompile(`\s+`).ReplaceAllString(name, "")
	if !safeMergeName(token) {
		return "", errors.New("MERGE_NAME_REQUIRED")
	}
	return token, nil
}

func buildNamespaceSources(iniRoots, existingChildren []string, includeVanilla bool) ([]namespaceMergeSource, error) {
	seen := map[string]struct{}{}
	take := func(iniPath string) bool {
		if isMasterIniPath(iniPath) {
			return false
		}
		resolved := resolveAgainst("", iniPath)
		if _, ok := seen[resolved]; ok {
			return false
		}
		seen[resolved] = struct{}{}
		return true
	}
	var groups [][]string
	filteredExisting := make([]string, 0, len(existingChildren))
	for _, child := range uniqueMergePaths(existingChildren) {
		if take(child) {
			filteredExisting = append(filteredExisting, child)
		}
	}
	grouped, err := groupInisBySwapSlot(filteredExisting)
	if err != nil {
		return nil, err
	}
	groups = append(groups, grouped...)
	for _, root := range iniRoots {
		inis, collectErr := collectEnabledINIs(root)
		if collectErr != nil {
			return nil, collectErr
		}
		filtered := make([]string, 0, len(inis))
		for _, ini := range inis {
			if take(ini) {
				filtered = append(filtered, ini)
			}
		}
		grouped, err = groupInisBySwapSlot(filtered)
		if err != nil {
			return nil, err
		}
		groups = append(groups, grouped...)
	}
	sources := make([]namespaceMergeSource, 0)
	index := 0
	for _, group := range groups {
		if len(group) == 0 {
			continue
		}
		slot := index
		if includeVanilla {
			slot = index + 1
		}
		for _, iniPath := range group {
			sources = append(sources, namespaceMergeSource{iniPath: iniPath, index: slot})
		}
		index++
	}
	return sources, nil
}

func groupInisBySwapSlot(iniPaths []string) ([][]string, error) {
	if len(iniPaths) == 0 {
		return nil, nil
	}
	type slotEntry struct {
		iniPath string
		slot    *int
	}
	entries := make([]slotEntry, len(iniPaths))
	allNull := true
	for i, iniPath := range iniPaths {
		raw, err := os.ReadFile(iniPath)
		if err != nil {
			return nil, err
		}
		slot := extractExistingSwapSlot(string(raw))
		entries[i] = slotEntry{iniPath: iniPath, slot: slot}
		if slot != nil {
			allNull = false
		}
	}
	if allNull {
		return [][]string{append([]string{}, iniPaths...)}, nil
	}
	var leftover []string
	indexed := make([]slotEntry, 0, len(entries))
	for _, entry := range entries {
		if entry.slot == nil {
			leftover = append(leftover, entry.iniPath)
			continue
		}
		indexed = append(indexed, entry)
	}
	slotOrder := []int{}
	seenSlot := map[int]struct{}{}
	bySlot := map[int][]string{}
	for _, entry := range indexed {
		slot := *entry.slot
		if _, ok := seenSlot[slot]; !ok {
			seenSlot[slot] = struct{}{}
			slotOrder = append(slotOrder, slot)
		}
		bySlot[slot] = append(bySlot[slot], entry.iniPath)
	}
	sort.Ints(slotOrder)
	result := make([][]string, 0, len(slotOrder))
	for i, slot := range slotOrder {
		group := append([]string{}, bySlot[slot]...)
		if i == 0 {
			group = append(group, leftover...)
		}
		result = append(result, group)
	}
	return result, nil
}

func extractExistingSwapSlot(text string) *int {
	matches := existingSwapSlotRE.FindAllStringSubmatch(text, -1)
	if len(matches) == 0 {
		return nil
	}
	minSlot := -1
	for _, match := range matches {
		slot, err := strconv.Atoi(match[1])
		if err != nil {
			continue
		}
		if minSlot < 0 || slot < minSlot {
			minSlot = slot
		}
	}
	if minSlot < 0 {
		return nil
	}
	return &minSlot
}

func disableForeignMasters(roots []string, keepPath string, created *[]mergeRollback) error {
	for _, root := range roots {
		inis, err := collectEnabledINIs(root)
		if err != nil {
			return err
		}
		for _, iniPath := range inis {
			if !isMasterIniPath(iniPath) || sameMergePath(iniPath, keepPath) {
				continue
			}
			if err := disableINIForMerge(iniPath, created); err != nil {
				return err
			}
		}
	}
	return nil
}
