{
  shamefullyHoist: true,
  autoInstallPeers: true,
  allowBuilds:
    {
      better-sqlite3: true,
      cbor-extract: true,
      electron: true,
      electron-winstaller: true,
      esbuild: true,
      koffi: true,
      lzma-native: true,
      sharp: true,
      workerd: true,
    },
  minimumReleaseAgeExclude:
    [
      '@ai-sdk/anthropic@4.0.29',
      '@ai-sdk/gateway@4.0.40',
      '@ai-sdk/openai-compatible@3.0.22',
      '@ai-sdk/openai@4.0.29',
      '@ai-sdk/provider-utils@5.0.20',
      '@ai-sdk/provider@4.0.5',
      ai@7.0.51,
    ],
}
