/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function collectFiles(paths: Array<string>, allowedExt: Array<string>): RawCollectionResult

export interface RawCollectionResult {
  files: Array<RawFileComponent>
  directories: Array<RawDirectoryComponent>
}

export interface RawDirectoryComponent {
  path: string
  name: string
  parentPath: string
}

export interface RawFileComponent {
  path: string
  name: string
  size: number
  parentPath: string
  fullPath: string
}
