/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeWatcher {
  constructor()
  watch(paths: Array<string>, depth: number, options: NativeWatcherOptions | undefined | null, callback: ((err: Error | null, arg: WatchEvent) => any)): void
  unwatch(): void
}

export declare function collectFiles(paths: Array<string>, allowedExt: Array<string>): RawCollectionResult

export interface NativeWatcherOptions {
  pollIntervalMs?: number
  compareContents?: boolean
}

export interface RawCollectionResult {
  files: Array<RawFileComponent>
  directories: Array<RawDirectoryComponent>
}

export interface RawDirectoryComponent {
  path: string
  name: string
  parentPath: string
}

export interface RawFileComponent {
  path: string
  name: string
  size: number
  parentPath: string
  fullPath: string
}

export interface WatchEvent {
  eventName: "create" | "modify" | "remove"
  path: string
}
