/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeFolderLock {
  constructor(path: string)
  lock(): void
  unlock(): void
  get isLocked(): boolean
  get path(): string
}

export declare class NativeWatcher {
  constructor()
  watch(paths: Array<string>, depth: number, options: NativeWatcherOptions | undefined | null, callback: ((err: Error | null, arg: WatchEvent) => any)): void
  unwatch(): void
}

export declare function collectFiles(paths: Array<string>, allowedExt: Array<string>): Promise<RawCollectionResult>

export declare function findFiles(paths: Array<string>, includeExt: Array<string>, excludeFileNames: Array<string>): Promise<Array<string>>

export declare function getLockingProcesses(path: string): Promise<Array<ProcessInfo>>

export interface NativeWatcherOptions {
  pollIntervalMs?: number
  compareContents?: boolean
}

export interface ProcessInfo {
  name: string
  pid: number
}

export interface RawCollectionResult {
  files: Array<RawFileComponent>
  directories: Array<RawDirectoryComponent>
}

export interface RawDirectoryComponent {
  path: string
  name: string
  parentPath: string
}

export interface RawFileComponent {
  path: string
  name: string
  size: number
  parentPath: string
  fullPath: string
}

export interface WatchEvent {
  eventName: "create" | "modify" | "remove"
  path: string
}
