// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddGame(game: string, modFolderPath: string, importer: string | null, linkedModFolderPath: string | null, gameInstallPath: string | null, gameExecutablePath: string | null): $CancellablePromise<void> {
    return $Call.ByID(3525228919, game, modFolderPath, importer, linkedModFolderPath, gameInstallPath, gameExecutablePath);
}

export function ApplyPreset(presetID: string): $CancellablePromise<$models.ApplyPresetResult> {
    return $Call.ByID(3262062829, presetID);
}

export function CancelPathSelection(selectionID: string): $CancellablePromise<void> {
    return $Call.ByID(499457967, selectionID);
}

export function ClassifyMergePacks(modPaths: string[] | null): $CancellablePromise<$models.ClassifyMergePacksResult> {
    return $Call.ByID(1496237314, modPaths);
}

export function CopyFolderToGroup(folderPath: string, groupPath: string, move: boolean): $CancellablePromise<string> {
    return $Call.ByID(4185922125, folderPath, groupPath, move);
}

export function CreatePreset(game: string, name: string, description: string | null, resolveConflicts: boolean): $CancellablePromise<$models.Preset> {
    return $Call.ByID(1246293305, game, name, description, resolveConflicts);
}

export function DeletePreset(presetID: string): $CancellablePromise<void> {
    return $Call.ByID(1359556226, presetID);
}

export function DisableAll(groupPath: string): $CancellablePromise<void> {
    return $Call.ByID(2494445277, groupPath);
}

export function DownloadFromURL(rawURL: string, groupPath: string): $CancellablePromise<string> {
    return $Call.ByID(2029509235, rawURL, groupPath);
}

export function DownloadGameBananaFile(props: $models.GameBananaDownloadProps): $CancellablePromise<string> {
    return $Call.ByID(2641213091, props);
}

export function EnableAll(groupPath: string): $CancellablePromise<void> {
    return $Call.ByID(987593284, groupPath);
}

export function ExclusiveToggle(modPath: string): $CancellablePromise<string> {
    return $Call.ByID(1184086638, modPath);
}

export function ExtractArchiveToGroup(archivePath: string, groupPath: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(4018183521, archivePath, groupPath, mode);
}

export function GetCharacters(game: string, searchModPreview: boolean | null): $CancellablePromise<$models.FolderGroup[] | null> {
    return $Call.ByID(3693627186, game, searchModPreview);
}

export function GetExpandedGroups(): $CancellablePromise<string[] | null> {
    return $Call.ByID(311802583);
}

export function GetGameBananaModID(modPath: string): $CancellablePromise<number | null> {
    return $Call.ByID(3339668722, modPath);
}

export function GetGamePath(game: string): $CancellablePromise<string | null> {
    return $Call.ByID(3640732727, game);
}

export function GetGames(): $CancellablePromise<$models.GameConfig[] | null> {
    return $Call.ByID(2946814265);
}

export function GetLastGame(): $CancellablePromise<string | null> {
    return $Call.ByID(579776092);
}

export function GetManualSubGroups(folderPath: string, searchModPreview: boolean | null): $CancellablePromise<$models.FolderGroup[] | null> {
    return $Call.ByID(2824731838, folderPath, searchModPreview);
}

export function GetMods(groupPath: string): $CancellablePromise<$models.FolderGroup> {
    return $Call.ByID(4094930719, groupPath);
}

export function GetModsLight(groupPath: string): $CancellablePromise<$models.FolderGroup> {
    return $Call.ByID(4233817785, groupPath);
}

export function GetPresetCreateConflicts(game: string): $CancellablePromise<$models.PresetConflict[] | null> {
    return $Call.ByID(3565121112, game);
}

export function GetPresets(game: string): $CancellablePromise<$models.Preset[] | null> {
    return $Call.ByID(1670580158, game);
}

export function GetPreviousFocusedGame(): $CancellablePromise<string | null> {
    return $Call.ByID(3656597010);
}

export function GetSubGroups(folderPath: string, searchModPreview: boolean | null): $CancellablePromise<$models.FolderGroup[] | null> {
    return $Call.ByID(2627066576, folderPath, searchModPreview);
}

export function HasSingleTopLevelDirectory(archivePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(693485740, archivePath);
}

export function HuiDownload(title: string, fileURL: string): $CancellablePromise<string> {
    return $Call.ByID(662049684, title, fileURL);
}

export function MergeMods(request: $models.MergeModsRequest): $CancellablePromise<$models.MergeModsResult> {
    return $Call.ByID(1224754907, request);
}

export function PastePreview(modPath: string, data: string, pasteType: string, existingPreviewPath: string | null): $CancellablePromise<string> {
    return $Call.ByID(1823802171, modPath, data, pasteType, existingPreviewPath);
}

export function PickExecutable(): $CancellablePromise<string | null> {
    return $Call.ByID(187351111);
}

export function PickFolder(): $CancellablePromise<string | null> {
    return $Call.ByID(34650643);
}

export function RemoveGame(game: string): $CancellablePromise<void> {
    return $Call.ByID(1397934864, game);
}

export function Rename(modPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(3614030880, modPath, newName);
}

export function ReorderGames(games: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(447395892, games);
}

export function ResolveArchiveExtractPrompt(requestID: string, mode: string | null): $CancellablePromise<void> {
    return $Call.ByID(1874196859, requestID, mode);
}

export function ResolveDownloadTarget(input: string, gameFilter: string | null): $CancellablePromise<$models.DownloadTarget | null> {
    return $Call.ByID(1344476751, input, gameFilter);
}

export function ResolveNteInstallPath(inputPath: string): $CancellablePromise<$models.NtePathResolution | null> {
    return $Call.ByID(1583521617, inputPath);
}

export function SelectFolder(game: string): $CancellablePromise<string | null> {
    return $Call.ByID(2955324014, game);
}

export function SelectFolderPath(selectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1057562085, selectionID);
}

export function SelectModManagerPath(selectionID: string, path: string, fileName: string | null): $CancellablePromise<void> {
    return $Call.ByID(1980053986, selectionID, path, fileName);
}

export function SetExpandedGroups(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(731356483, paths);
}

export function SetGamePath(game: string, modFolderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3911271203, game, modFolderPath);
}

export function SetLastGame(game: string): $CancellablePromise<void> {
    return $Call.ByID(2139169728, game);
}

export function SetManualSubGroup(modPath: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(609097861, modPath, enabled);
}

export function SetNteLauncherPath(game: string, launcherPath: string): $CancellablePromise<void> {
    return $Call.ByID(3219505108, game, launcherPath);
}

export function StartNteLauncher(game: string): $CancellablePromise<void> {
    return $Call.ByID(1044309099, game);
}

export function Toggle(modPath: string): $CancellablePromise<string> {
    return $Call.ByID(27817486, modPath);
}

export function UpdateGame(game: string, updates: $models.GameUpdates): $CancellablePromise<void> {
    return $Call.ByID(1683455013, game, updates);
}

export function UpdatePresetName(presetID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2641984507, presetID, newName);
}

export function UpdateToggleKey(modPath: string, iniFileName: string, sectionName: string, variable: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2401127578, modPath, iniFileName, sectionName, variable, value);
}

export function WatchCharacter(characterPath: string): $CancellablePromise<void> {
    return $Call.ByID(1675748592, characterPath);
}

export function WatchGame(game: string): $CancellablePromise<void> {
    return $Call.ByID(3149662823, game);
}
