// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApplyPresetResult {
    "presetId": string;
    "applied": string[] | null;
    "skipped": string[] | null;
    "missing": MissingPresetItem[] | null;
}

export interface ClassifyMergePacksResult {
    "packs": MergePackClassification[] | null;
    "hashOverlap": boolean;
    "warnings": string[] | null;
}

export interface DownloadTarget {
    "game": string;
    "group": FolderGroup;
    "score": number;
}

export interface FolderGroup {
    "name": string;
    "path": string;
    "mods": ModInfo[] | null;
    "preview"?: string | null;
    "modCount": number;
    "enabledModCount": number;
    "isManualSubGroup"?: boolean;
    "hasSubGroups"?: boolean;
    "hasManualSubGroups"?: boolean;
}

export interface GameBananaDownloadProps {
    "itemId": number;
    "fileId": number;
    "modelName"?: string;
}

export interface GameConfig {
    "game": string;
    "modFolderPath": string;
    "importer": string | null;
    "linkedModFolderPath": string | null;
    "gameInstallPath": string | null;
    "gameExecutablePath": string | null;
    "nteLauncherPath": string | null;
    "order": number;
}

export interface GameUpdates {
    "modFolderPath": string;
    "importer": string | null;
    "linkedModFolderPath": string | null;
    "gameInstallPath": string | null;
    "gameExecutablePath": string | null;
}

export interface IniResult {
    "name": string;
    "path": string;
    "toggleKeys": ToggleKey[] | null;
    "hasToggleKey": boolean;
}

export interface MergeModsRequest {
    "groupPath": string;
    "placement": string;
    "packName": string;
    "root": MergePlanNode;
}

export interface MergeModsResult {
    "outputPath": string;
}

export interface MergePackClassification {
    "path": string;
    "name": string;
    "family": string;
    "dialect": string;
    "primaryIniPath": string | null;
    "hashes": string[] | null;
    "objectGuid": string | null;
    "allowsClassic": boolean;
    "warnings": string[] | null;
}

export interface MergePlanNode {
    "kind": string;
    "path"?: string;
    "id"?: string;
    "engine"?: string;
    "name"?: string;
    "forwardKey"?: string;
    "backKey"?: string;
    "includeVanilla"?: boolean;
    "children"?: MergePlanNode[] | null;
}

export interface MissingPresetItem {
    "modKey": string;
    "expectedFolderName": string;
    "expectedRelativePath": string;
}

export interface ModInfo {
    "id": string;
    "name": string;
    "path": string;
    "isEnabled": boolean;
    "preview"?: string | null;
    "mtime": number;
    "size": number;
    "inis": IniResult[] | null;
}

export interface NtePathResolution {
    "gameRootPath": string;
    "executablePath": string;
    "modFolderPath": string;
    "linkedModFolderPath": string;
    "requiresElevation": boolean;
}

export interface Preset {
    "id": string;
    "game": string;
    "name": string;
    "description": string | null;
    "createdAt": string;
    "updatedAt": string;
    "version": number;
    "isLegacy": boolean;
}

export interface PresetConflict {
    "modKey": string;
    "candidates": PresetConflictCandidate[] | null;
}

export interface PresetConflictCandidate {
    "actualPath": string;
    "relativePath": string;
    "folderName": string;
    "isEnabled": boolean;
}

export interface ToggleKey {
    "sectionName": string;
    "iniFileName": string;
    "key"?: string | null;
    "back"?: string | null;
    "type"?: string | null;
    "variable": string;
    "values": string[] | null;
    "currentValue"?: string | null;
}
