// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdvancedRow {
    key: string;
    value: string | null;
}

export interface Bounds {
    x: number;
    y: number;
    width: number;
    height: number;
}
