// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Setting is the Go port of Electron desktop/src/main/setting.ts.
 * It reads and writes typed settings through the shipped db.Client.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AdvancedGetAll(): $CancellablePromise<$models.AdvancedRow[] | null> {
    return $Call.ByID(1083666835);
}

export function AdvancedSet(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1233429164, key, value);
}

export function ClearImageCache(): $CancellablePromise<void> {
    return $Call.ByID(1234669302);
}

export function Get(key: string): $CancellablePromise<any> {
    return $Call.ByID(508399762, key);
}

export function GetArchiveExtractPathMode(): $CancellablePromise<string> {
    return $Call.ByID(3572129193);
}

export function GetAutoUpdateMode(): $CancellablePromise<string> {
    return $Call.ByID(2268804527);
}

export function GetBisectPreserveD3dx(): $CancellablePromise<boolean> {
    return $Call.ByID(3386004681);
}

export function GetBounds(): $CancellablePromise<$models.Bounds | null> {
    return $Call.ByID(2634900291);
}

export function GetCharacterSidebarWidth(): $CancellablePromise<number> {
    return $Call.ByID(629338697);
}

export function GetCopyShaderFixesOnEnable(): $CancellablePromise<boolean> {
    return $Call.ByID(414090619);
}

export function GetDefaultStartPage(): $CancellablePromise<string> {
    return $Call.ByID(1971104646);
}

export function GetDeleteArchiveAfterExtract(): $CancellablePromise<boolean> {
    return $Call.ByID(1108885226);
}

export function GetDisabledPrefixStyle(): $CancellablePromise<string> {
    return $Call.ByID(1305649187);
}

export function GetDownloadBandwidthLimitMibps(): $CancellablePromise<number> {
    return $Call.ByID(3168886323);
}

export function GetDownloadConcurrency(): $CancellablePromise<number> {
    return $Call.ByID(1871191717);
}

export function GetEnvironment(): $CancellablePromise<string> {
    return $Call.ByID(3526199791);
}

export function GetExposure(): $CancellablePromise<number> {
    return $Call.ByID(952204411);
}

export function GetGridFixedCardWidth(): $CancellablePromise<number> {
    return $Call.ByID(2893528006);
}

export function GetGridFixedColumnCount(): $CancellablePromise<number> {
    return $Call.ByID(2303978405);
}

export function GetGridLayoutMode(): $CancellablePromise<string> {
    return $Call.ByID(1953386871);
}

export function GetGridResponsiveBaseWidth(): $CancellablePromise<number> {
    return $Call.ByID(3404634775);
}

export function GetImageCacheSize(): $CancellablePromise<number> {
    return $Call.ByID(1039924778);
}

export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(1564751264);
}

export function GetLogLevel(): $CancellablePromise<string> {
    return $Call.ByID(3695300174);
}

export function GetMany(
    keys: string[] | null,
): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4122638309, keys);
}

export function GetMoveFolderInsteadOfCopy(): $CancellablePromise<boolean> {
    return $Call.ByID(3329291475);
}

export function GetMoveTransferPageWhenStartTransfer(): $CancellablePromise<boolean> {
    return $Call.ByID(1401619234);
}

export function GetNameSortPolicy(): $CancellablePromise<string> {
    return $Call.ByID(1632848559);
}

export function GetOpenConsole(): $CancellablePromise<boolean> {
    return $Call.ByID(711051875);
}

export function GetPersistToggles(): $CancellablePromise<boolean> {
    return $Call.ByID(2233531507);
}

export function GetPowerSaveBlockInTransfer(): $CancellablePromise<boolean> {
    return $Call.ByID(3990156507);
}

export function GetRunInBackground(): $CancellablePromise<boolean> {
    return $Call.ByID(3772225476);
}

export function GetRunOnStartup(): $CancellablePromise<boolean> {
    return $Call.ByID(3721850451);
}

export function GetSearchModPreview(): $CancellablePromise<boolean> {
    return $Call.ByID(474623186);
}

export function GetSettingBounds(): $CancellablePromise<$models.Bounds | null> {
    return $Call.ByID(1101377951);
}

export function GetSidebarLayout(): $CancellablePromise<string> {
    return $Call.ByID(2594928568);
}

export function GetToggleViewerAutoGenerate(): $CancellablePromise<boolean> {
    return $Call.ByID(2820907456);
}

export function GetToggleViewerHotkey(): $CancellablePromise<string> {
    return $Call.ByID(858691434);
}

export function GetToneMapping(): $CancellablePromise<string> {
    return $Call.ByID(41504140);
}

export function GetUploadConcurrency(): $CancellablePromise<number> {
    return $Call.ByID(14693926);
}

export function GetVirtualizationEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3786865508);
}

export function GetVirtualizationThreshold(): $CancellablePromise<number> {
    return $Call.ByID(1559602778);
}

export function Set(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(325680014, key, value);
}

export function SetArchiveExtractPathMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3298873909, mode);
}

export function SetAutoUpdateMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2025920643, mode);
}

export function SetBisectPreserveD3dx(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3880224421, enabled);
}

export function SetBounds(bounds: $models.Bounds): $CancellablePromise<void> {
    return $Call.ByID(542786959, bounds);
}

export function SetCharacterSidebarWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(2376367861, width);
}

export function SetCopyShaderFixesOnEnable(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(387661751, enabled);
}

export function SetDefaultStartPage(page: string): $CancellablePromise<void> {
    return $Call.ByID(2234889250, page);
}

export function SetDeleteArchiveAfterExtract(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(287258382, enabled);
}

export function SetDisabledPrefixStyle(style: string): $CancellablePromise<void> {
    return $Call.ByID(261935599, style);
}

export function SetDownloadBandwidthLimitMibps(mibps: number): $CancellablePromise<void> {
    return $Call.ByID(3019787959, mibps);
}

export function SetDownloadConcurrency(concurrency: number): $CancellablePromise<void> {
    return $Call.ByID(4264680889, concurrency);
}

export function SetEnvironment(environment: string): $CancellablePromise<void> {
    return $Call.ByID(1924001147, environment);
}

export function SetExposure(exposure: number): $CancellablePromise<void> {
    return $Call.ByID(2436204535, exposure);
}

export function SetGridFixedCardWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(3285148426, width);
}

export function SetGridFixedColumnCount(count: number): $CancellablePromise<void> {
    return $Call.ByID(1112687473, count);
}

export function SetGridLayoutMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3568853987, mode);
}

export function SetGridResponsiveBaseWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(2167638627, width);
}

export function SetLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(3304330476, language);
}

export function SetLogLevel(level: string): $CancellablePromise<void> {
    return $Call.ByID(1596331674, level);
}

export function SetMoveFolderInsteadOfCopy(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4016745223, enabled);
}

export function SetMoveTransferPageWhenStartTransfer(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3156162366, enabled);
}

export function SetNameSortPolicy(policy: string): $CancellablePromise<void> {
    return $Call.ByID(3092237475, policy);
}

export function SetOpenConsole(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2043037079, enabled);
}

export function SetPersistToggles(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(356772319, enabled);
}

export function SetPowerSaveBlockInTransfer(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2895112135, enabled);
}

export function SetRunInBackground(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3492312920, enabled);
}

export function SetRunOnStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1385248759, enabled);
}

export function SetSearchModPreview(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1138809374, enabled);
}

export function SetSettingBounds(bounds: $models.Bounds): $CancellablePromise<void> {
    return $Call.ByID(153625819, bounds);
}

export function SetSidebarLayout(mode: string): $CancellablePromise<void> {
    return $Call.ByID(4002521052, mode);
}

export function SetToggleViewerAutoGenerate(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3381568932, enabled);
}

export function SetToggleViewerHotkey(hotkey: string): $CancellablePromise<void> {
    return $Call.ByID(3126185854, hotkey);
}

export function SetToneMapping(toneMapping: string): $CancellablePromise<void> {
    return $Call.ByID(1214804888, toneMapping);
}

export function SetUploadConcurrency(concurrency: number): $CancellablePromise<void> {
    return $Call.ByID(4293462178, concurrency);
}

export function SetVirtualizationEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(732173016, enabled);
}

export function SetVirtualizationThreshold(threshold: number): $CancellablePromise<void> {
    return $Call.ByID(3617853102, threshold);
}
