/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DecodedDdsRgba8 {
  width: number
  height: number
  layers: number
  mipmaps: number
  format: string
  data: Buffer
}

export declare function decodeDdsToRgba8(path: string): Promise<DecodedDdsRgba8>

export declare function encodeRgba8ToDds(request: EncodeRgba8ToDdsRequest): Promise<EncodeRgba8ToDdsResult>

export interface EncodeRgba8ToDdsRequest {
  path: string
  width: number
  height: number
  data: Buffer
  outputFormat: string
  backup: boolean
  generateMipmaps: boolean
}

export interface EncodeRgba8ToDdsResult {
  path: string
  width: number
  height: number
  outputFormat: string
  backupCreated: boolean
}

export declare function resizeTextures(request: TextureResizeRequest): Promise<TextureResizeResult>

export interface TextureResizeFileResult {
  filePath: string
  status: string
  originalWidth: number
  originalHeight: number
  outputWidth: number
  outputHeight: number
  originalFormat: string
  outputFormat: string
  backupCreated: boolean
  message?: string
}

export interface TextureResizeRequest {
  targetPath: string
  mode: string
  operation?: string
  percent?: number
  customWidth?: number
  customHeight?: number
  outputFormat?: string
  backup?: boolean
}

export interface TextureResizeResult {
  targetPath: string
  processed: number
  updated: number
  skipped: number
  failed: number
  files: Array<TextureResizeFileResult>
}
