/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function resizeTextures(request: TextureResizeRequest): Promise<TextureResizeResult>

export interface TextureResizeFileResult {
  filePath: string
  status: string
  originalWidth: number
  originalHeight: number
  outputWidth: number
  outputHeight: number
  originalFormat: string
  outputFormat: string
  backupCreated: boolean
  message?: string
}

export interface TextureResizeRequest {
  targetPath: string
  mode: string
  operation?: string
  percent?: number
  customWidth?: number
  customHeight?: number
  outputFormat?: string
  backup?: boolean
}

export interface TextureResizeResult {
  targetPath: string
  processed: number
  updated: number
  skipped: number
  failed: number
  files: Array<TextureResizeFileResult>
}
