// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";

export interface BisectSnapshot {
    "status": BisectStatus;
    "game": string;
    "modRootPath": string | null;
    "round": number;
    "batchSize": number;
    "candidates": string[] | null;
    "currentBatch": string[] | null;
    "excludePaths": string[] | null;
    "undoStackDepth": number;
    "finalBadPath": string | null;
    "error": string | null;
}

export enum BisectStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BisectIdle = "idle",
    BisectScanning = "scanning",
    BisectRound = "round",
    BisectDone = "done",
    BisectReverting = "reverting",
    BisectCancelled = "cancelled",
};

export interface BlendBoneInfo {
    "id": number;
    "vertexCount": number;
}

export interface BodyShapeChangeSummary {
    "amount": number;
    "axisScale": number[] | null;
    "movedVertices": number;
    "maxDisplacement": number;
}

export interface BodyShapeExportInput {
    "modRoot": string;
    "positionPath": string;
    "positionStride": number;
    "positions": number[] | null;
    "vectorPath"?: string | null;
    "vectorLayout": string | null;
    "weights"?: number[] | null;
    "amount"?: number | null;
    "axisScale"?: number[] | null;
    "writeChangeLog"?: boolean | null;
    "changeSummary"?: BodyShapeChangeSummary | null;
}

export interface BodyShapeExportResult {
    "positionPath": string;
    "positionBytes": number;
    "vectorPath"?: string | null;
    "vectorBytes"?: number | null;
    "changeLogPath"?: string | null;
    "modRoot"?: string | null;
    "sourceModPath"?: string | null;
}

export interface BodyShapeLoadResult {
    "modRoot": string;
    "iniPath": string;
    "meshes": BodyShapeMeshCandidate[] | null;
}

export interface BodyShapeMeshCandidate {
    "id": string;
    "name": string;
    "positionPath": string;
    "positionRelativePath": string;
    "positionStride": number;
    "vertexCount": number;
    "positions": number[] | null;
    "indices"?: number[] | null;
    "indexPath"?: string | null;
    "indexRelativePath"?: string | null;
    "vectorPath"?: string | null;
    "vectorRelativePath"?: string | null;
    "vectorStride"?: number | null;
    "vectorLayout": string | null;
    "glbMeshNames": string[] | null;
    "blendPath"?: string | null;
    "blendRelativePath"?: string | null;
    "blendStride"?: number | null;
    "blendBytes"?: string | null;
    "bones": BlendBoneInfo[] | null;
}

export interface CreateScriptPresetInput {
    "name": string;
    "scriptIds": string[] | null;
}

export interface DiversificationState {
    "hasBackup": boolean;
    "backupPath": string | null;
}

export interface Fixer4001BuildInput {
    "provider": string;
    "version": string;
    "importerKey": string;
    "importerPath"?: string | null;
}

export interface Fixer4001ImporterInput {
    "importerKey": string;
    "importerPath"?: string | null;
}

export interface Fixer4001PathInput {
    "importerPath"?: string | null;
}

export interface Fixer4001Result {
    "success": boolean;
    "errorMessage"?: string | null;
    "backupPath"?: string | null;
}

export interface Fixer4001State {
    "isBuilding": boolean;
    "activeTask": string | null;
    "progress": string;
    "errorMessage": string;
}

export interface GitHubRateState {
    "limit": number;
    "remaining": number;
    "reset": number;
    "used": number;
    "resource": string;
    "updatedAt": string;
}

export interface ImporterWriteAccess {
    "writable": boolean;
    "locked": boolean;
    "requiresElevation": boolean;
    "processes": platform$0.ProcessInfo[] | null;
}

export interface ModelViewerAnimationClip {
    "id": string;
    "label": string;
    "variableIds": string[] | null;
    "fps": number;
    "frameStart": number;
    "frameEnd": number;
    "loop": boolean;
    "frames": ModelViewerAnimationFrame[] | null;
}

export interface ModelViewerAnimationFrame {
    "index": number;
    "time": number;
    "values": { [_ in string]?: any } | null;
}

export type ModelViewerDNF = (ModelViewerDNFClause[] | null)[] | null;

export interface ModelViewerDNFClause {
    "var": string;
    "value": string;
    "negate": boolean;
}

export interface ModelViewerMenuEffect {
    "when"?: ModelViewerMenuGuard | null;
    "var": string;
    "value": string;
}

export interface ModelViewerMenuGuard {
    "var": string;
    "op": string;
    "value": string;
}

export interface ModelViewerMeshTransport {
    "id": string;
    "component": string;
    "positionsUrl": string;
    "normalsUrl"?: string;
    "tangentsUrl"?: string;
    "uvsUrl"?: string;
    "indicesUrl": string;
    "conditions": ModelViewerDNF;
    "texKey": string | null;
    "textureVariants": ModelViewerTextureVariant[] | null;
    "normalMapKey": string | null;
    "normalMapVariants": ModelViewerTextureVariant[] | null;
    "lightMapKey": string | null;
    "lightMapVariants": ModelViewerTextureVariant[] | null;
    "materialMapKey": string | null;
    "materialMapVariants": ModelViewerTextureVariant[] | null;
    "shapeTargets": ModelViewerShapeTarget[] | null;
    "positionVariants": ModelViewerPositionVariant[] | null;
}

export interface ModelViewerPositionVariant {
    "conditions": ModelViewerDNF;
    "positionsUrl": string;
}

export interface ModelViewerShapeTarget {
    "var": string;
    "positionsUrl": string;
    "mode"?: string;
    "lowPositionsUrl"?: string;
}

export interface ModelViewerSlider {
    "min": number;
    "max": number;
    "step": number;
}

export interface ModelViewerStateRule {
    "var": string;
    "value": string;
    "conditions": ModelViewerDNF;
}

export interface ModelViewerTextureTransport {
    "url": string;
    "role": string;
}

export interface ModelViewerTextureVariant {
    "conditions": ModelViewerDNF;
    "texKey": string;
}

export interface ModelViewerTransport {
    "memorySessionId": string;
    "iniPath": string;
    "modPath": string;
    "name": string;
    "materialProfile"?: string;
    "meshes": ModelViewerMeshTransport[] | null;
    "textures": { [_ in string]?: ModelViewerTextureTransport } | null;
    "variables": ModelViewerVariable[] | null;
    "defaultState": { [_ in string]?: any } | null;
    "stateRules": ModelViewerStateRule[] | null;
    "uiAssets": ModelViewerUIAssets;
    "animations": ModelViewerAnimationClip[] | null;
}

export interface ModelViewerUIAssets {
    "backgroundPath"?: string;
    "slotPath"?: string;
    "slotHoverPath"?: string;
    "slotActivePath"?: string;
}

export interface ModelViewerVariable {
    "id": string;
    "label": string;
    "defaultValue": any;
    "values": ModelViewerVariableValue[] | null;
    "order": number;
    "slot"?: number;
    "iconPath"?: string;
    "controlType"?: string;
    "slider"?: ModelViewerSlider | null;
    "effects"?: ModelViewerMenuEffect[] | null;
}

export interface ModelViewerVariableValue {
    "value": any;
    "label": string;
}

export interface PersistModelViewerResult {
    "updatedVariables": string[] | null;
}

export interface TextureResizeFileResult {
    "filePath": string;
    "status": string;
    "originalWidth": number;
    "originalHeight": number;
    "outputWidth": number;
    "outputHeight": number;
    "originalFormat": string;
    "outputFormat": string;
    "backupCreated": boolean;
    "message"?: string | null;
}

export interface TextureResizeFileRunInput {
    "filePath": string;
    "settings": TextureResizeSettings;
}

export interface TextureResizeListItem {
    "filePath": string;
    "relativePath": string;
    "fileName": string;
    "fileSize": number;
    "format": string;
    "colorSpace": string;
    "layerCount": number;
    "mipLevelCount": number;
    "originalWidth": number;
    "originalHeight": number;
    "targetWidth": number;
    "targetHeight": number;
    "canResize": boolean;
    "canUpscale": boolean;
    "canConvertFormat": boolean;
    "canProcess": boolean;
    "availableOutputFormats": string[] | null;
    "outputFormatDefault": string;
    "formatConversionMessage"?: string | null;
    "message"?: string | null;
}

export interface TextureResizeModInput {
    "settings": TextureResizeSettings;
}

export interface TextureResizeProgressEvent {
    "status": string;
    "operation"?: string | null;
    "filePath"?: string | null;
    "fileName"?: string | null;
    "totalFiles"?: number | null;
    "processedFiles"?: number | null;
    "error"?: string | null;
}

export interface TextureResizeResult {
    "targetPath": string;
    "processed": number;
    "updated": number;
    "skipped": number;
    "failed": number;
    "files": TextureResizeFileResult[] | null;
}

export interface TextureResizeRunInput {
    "targetPath": string;
    "settings": TextureResizeSettings;
}

export interface TextureResizeSettings {
    "mode": string;
    "operation": string;
    "percent": number;
    "customWidth": number;
    "customHeight": number;
    "outputFormat": string;
    "backup": boolean;
    "upscaleScale": number;
    "upscaleModel": string;
}

export interface TextureResizeSettingsPatch {
    "mode"?: string | null;
    "operation"?: string | null;
    "percent"?: number | null;
    "customWidth"?: number | null;
    "customHeight"?: number | null;
    "outputFormat"?: string | null;
    "backup"?: boolean | null;
    "upscaleScale"?: number | null;
    "upscaleModel"?: string | null;
}

export interface TextureUpscaleRuntimeStatus {
    "installed": boolean;
    "version": string | null;
    "binaryPath": string | null;
    "modelsPath": string | null;
    "needsInstall": boolean;
}

export interface TextureUpscaleRuntimeStatuses {
    "realesrgan": TextureUpscaleRuntimeStatus;
    "realcugan": TextureUpscaleRuntimeStatus;
}

export interface ToggleViewerState {
    "isRunning": boolean;
    "mode": string | null;
}

export interface TouchAdvancedSettings {
    "radius": number;
    "strength": number;
    "damping": number;
    "spring": number;
    "maxOffset": number;
    "falloff": number;
}

export interface TouchApplyResult {
    "sessionId": string;
    "outputModRoot": string;
    "sourceModRoot": string;
    "reenableSourceOnRollback": boolean;
    "disabled": boolean;
    "validation": TouchValidationResult;
    "warnings": string[] | null;
}

export interface TouchBoneComponentSelection {
    "componentId": string;
    "zones": TouchBoneZoneSelection[] | null;
}

export interface TouchBoneZoneSelection {
    "boneId": number;
    "channel": number | null;
    "label"?: string | null;
}

export interface TouchComponentAnalysis {
    "id": string;
    "name": string;
    "kind": string;
    "interactiveCandidate": boolean;
    "supportGrade": string;
    "supportReasons": string[] | null;
    "positionResourceName": string;
    "positionRelativePath": string;
    "positionPath": string;
    "positionStride": number;
    "vertexCount": number;
    "indexResourceName"?: string | null;
    "indexRelativePath"?: string | null;
    "indexPath"?: string | null;
    "indexRelativePaths"?: string[] | null;
    "indexPaths"?: string[] | null;
    "indexFormats"?: (string | null)[] | null;
    "indexFormat"?: string | null;
    "indexCount": number;
    "blendSectionName"?: string | null;
    "ibSectionName"?: string | null;
    "ibHash"?: string | null;
    "variantKey"?: string | null;
    "variantCondition"?: string | null;
    "drawRanges": TouchDrawRange[] | null;
    "objectMaps": TouchObjectMapEntry[] | null;
    "blendRelativePath"?: string | null;
    "blendPath"?: string | null;
    "blendStride"?: number | null;
    "bones": BlendBoneInfo[] | null;
}

export interface TouchComponentDraft {
    "componentId": string;
    "interactive": boolean;
    "objectId": number;
    "zones": TouchZoneSpec[] | null;
    "confidence": number;
    "warnings": string[] | null;
}

export interface TouchComponentInspection {
    "id": string;
    "name": string;
    "kind": string;
    "supportGrade": string;
    "interactiveCandidate": boolean;
    "vertexCount": number;
    "indexCount": number;
    "variantKey"?: string | null;
    "variantCondition"?: string | null;
    "objectMaps": TouchObjectMapEntry[] | null;
    "hasBlend": boolean;
    "bones": BlendBoneInfo[] | null;
}

export interface TouchDraft {
    "sessionId": string;
    "createdAt": string;
    "sourceModRoot": string;
    "analysis": TouchModAnalysis;
    "components": TouchComponentDraft[] | null;
    "visionUsed": boolean;
    "modelName": string;
    "llm": TouchProfileLLMSettings;
    "promptVersion": string;
    "runtimeVersion": string;
    "canAutoApply": boolean;
    "warnings": string[] | null;
}

export interface TouchDrawRange {
    "firstIndex": number;
    "indexCount": number;
    "baseVertex": number;
    "label"?: string | null;
    "conditionText"?: string | null;
}

export interface TouchMeshPreview {
    "sessionId": string;
    "componentId": string;
    "vertexCount": number;
    "positions": number[] | null;
    "indices": number[] | null;
    "bones": BlendBoneInfo[] | null;
    "blendStride"?: number | null;
    "blendBytes"?: string | null;
}

export interface TouchModAnalysis {
    "modRoot": string;
    "sourceRoot": string;
    "modRootRelativeToSource": string;
    "iniPath": string;
    "iniRelativePath": string;
    "sourceFilesRelativePaths": string[] | null;
    "supportGrade": string;
    "supportReasons": string[] | null;
    "components": TouchComponentAnalysis[] | null;
    "meshHash": string;
    "iniHash": string;
}

export interface TouchModInspection {
    "sessionId": string;
    "modRoot": string;
    "iniRelativePath": string;
    "sourceFilesRelativePaths": string[] | null;
    "supportGrade": string;
    "supportReasons": string[] | null;
    "components": TouchComponentInspection[] | null;
}

export interface TouchObjectMapEntry {
    "firstIndex": number;
    "indexCount": number;
    "objectMode": number;
    "objectId": number;
    "label": string;
}

export interface TouchPreviewZone {
    "id": string;
    "label": string;
    "channel": number;
    "confidence": number;
    "center": number[];
    "radius": number[];
    "source": string;
    "settings": TouchZoneSettings;
    "seedVertices"?: number[] | null;
    "weights": number[] | null;
}

export interface TouchProfileAnalyzeInput {
    "sessionId": string;
    "componentIds": string[] | null;
    "mode"?: string | null;
    "boneSelections"?: TouchBoneComponentSelection[] | null;
    "weightThreshold"?: number[] | null;
}

export interface TouchProfileApplyInput {
    "sessionId": string;
    "force"?: boolean;
}

export interface TouchProfileLLMSettings {
    "protocol": string;
    "endpoint": string;
    "model": string;
    "reasoning": string;
}

export interface TouchProfileLoadInput {
    "modPath": string;
}

export interface TouchProfileOK {
    "ok": boolean;
}

export interface TouchProfilePreview {
    "sessionId": string;
    "componentId": string;
    "vertexCount": number;
    "positions": number[] | null;
    "indices": number[] | null;
    "zones": TouchPreviewZone[] | null;
}

export interface TouchProfilePreviewInput {
    "sessionId": string;
    "componentId": string;
}

export interface TouchProfileRollbackInput {
    "sessionId": string;
    "outputModRoot": string;
    "sourceModRoot": string;
    "reenableSourceOnRollback": boolean;
}

export interface TouchProfileUpdateZoneSettingsInput {
    "sessionId": string;
    "componentId": string;
    "zoneId": string;
    "settings": TouchZoneSettings;
}

export interface TouchRollbackResult {
    "outputModRoot": string;
    "sourceModRoot": string;
    "removedOutput": boolean;
    "reenabledSource": boolean;
}

export interface TouchValidationIssue {
    "level": string;
    "code": string;
    "message": string;
    "componentId"?: string | null;
}

export interface TouchValidationResult {
    "ok": boolean;
    "issues": TouchValidationIssue[] | null;
}

export interface TouchZoneSettings {
    "maskStrength": number;
    "maskCurve": number;
    "maskRadiusScale": number;
    "maskCoreAttenuation": string;
    "strengthPreset": string;
    "physicsPreset": string;
    "advanced": TouchAdvancedSettings;
}

export interface TouchZoneSpec {
    "id": string;
    "label": string;
    "channel": number;
    "confidence": number;
    "center": number[];
    "radius": number[];
    "source": string;
    "settings": TouchZoneSettings;
    "seedVertices"?: number[] | null;
}

export interface WuwaBackupFile {
    "currentPath": string;
    "originalPath": string;
    "timestamp": string;
    "groupKey": string;
}

export interface WuwaBackupGroup {
    "groupKey": string;
    "files": WuwaBackupFile[] | null;
}

export interface WuwaBackupSize {
    "bytes": number;
    "count": number;
}

export interface WuwaFixerOptions {
    "derivedHashes": boolean;
    "stableTexture": boolean;
    "aemeathMech": boolean;
    "rendering33": boolean;
    "aeroFix": string;
}

export interface WuwaFixerPrepareResult {
    "supported": boolean;
    "installed": boolean;
    "installedVersion": string | null;
    "latestVersion": string | null;
    "binaryPath": string | null;
    "updateAvailable": boolean;
    "rateState": GitHubRateState | null;
    "rateLimited": boolean;
    "nextCheckAt": string | null;
    "needsInstall": boolean;
    "checkedRemotely": boolean;
}

export interface WuwaFixerStatus {
    "supported": boolean;
    "installed": boolean;
    "installedVersion": string | null;
    "latestVersion": string | null;
    "binaryPath": string | null;
    "updateAvailable": boolean;
    "rateState": GitHubRateState | null;
    "rateLimited": boolean;
    "nextCheckAt": string | null;
}
