// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BisectCancel(): $CancellablePromise<$models.BisectSnapshot> {
    return $Call.ByID(3782118482);
}

export function BisectFinalize(
    keepDisabled: string[] | null,
): $CancellablePromise<$models.BisectSnapshot> {
    return $Call.ByID(789146642, keepDisabled);
}

export function BisectGetState(): $CancellablePromise<$models.BisectSnapshot | null> {
    return $Call.ByID(3843076473);
}

export function BisectRecover(game: string): $CancellablePromise<number> {
    return $Call.ByID(108540924, game);
}

export function BisectRespond(fixed: boolean): $CancellablePromise<$models.BisectSnapshot> {
    return $Call.ByID(883061117, fixed);
}

export function BisectStart(
    game: string,
    excludePaths: string[] | null,
): $CancellablePromise<$models.BisectSnapshot> {
    return $Call.ByID(2715752484, game, excludePaths);
}

export function BisectUndoLastRound(): $CancellablePromise<$models.BisectSnapshot> {
    return $Call.ByID(29486810);
}

export function BisectValidateExcludePath(
    game: string,
    inputPath: string,
): $CancellablePromise<string> {
    return $Call.ByID(1760439743, game, inputPath);
}

export function BodyShapeExport(
    input: $models.BodyShapeExportInput,
): $CancellablePromise<$models.BodyShapeExportResult> {
    return $Call.ByID(891411225, input);
}

export function BodyShapeLoadMod(
    modPath: string,
): $CancellablePromise<$models.BodyShapeLoadResult> {
    return $Call.ByID(3073495713, modPath);
}

export function CancelRun(): $CancellablePromise<boolean> {
    return $Call.ByID(1446463045);
}

export function CleanupModelViewer(memorySessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1566572389, memorySessionID);
}

export function CreatePreset(input: $models.CreateScriptPresetInput): $CancellablePromise<void> {
    return $Call.ByID(803309189, input);
}

export function DeletePreset(presetID: string): $CancellablePromise<void> {
    return $Call.ByID(1561152790, presetID);
}

export function DeleteScript(scriptID: string): $CancellablePromise<void> {
    return $Call.ByID(3991246962, scriptID);
}

export function FourThousandOneFixerBuildDll(
    input: $models.Fixer4001BuildInput,
): $CancellablePromise<$models.Fixer4001Result> {
    return $Call.ByID(7776532, input);
}

export function FourThousandOneFixerCheckImporterWriteAccess(
    input: $models.Fixer4001PathInput,
): $CancellablePromise<$models.ImporterWriteAccess> {
    return $Call.ByID(2166092143, input);
}

export function FourThousandOneFixerDiversifyDllPadding(
    input: $models.Fixer4001ImporterInput,
): $CancellablePromise<$models.Fixer4001Result> {
    return $Call.ByID(477628836, input);
}

export function FourThousandOneFixerGetDiversificationState(
    input: $models.Fixer4001PathInput,
): $CancellablePromise<$models.DiversificationState> {
    return $Call.ByID(1641578396, input);
}

export function FourThousandOneFixerGetProviderReleases(
    provider: string,
): $CancellablePromise<string[] | null> {
    return $Call.ByID(1762686795, provider);
}

export function FourThousandOneFixerGetState(): $CancellablePromise<$models.Fixer4001State> {
    return $Call.ByID(279214897);
}

export function FourThousandOneFixerRestoreDiversifiedDll(
    input: $models.Fixer4001PathInput,
): $CancellablePromise<$models.Fixer4001Result> {
    return $Call.ByID(631357502, input);
}

export function FourThousandOneFixerUpdateReleases(): $CancellablePromise<void> {
    return $Call.ByID(232456755);
}

export function GetPersistLogs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2123295157);
}

export function GetPresets(): $CancellablePromise<db$0.ScriptPresetWithScripts[] | null> {
    return $Call.ByID(847284554);
}

export function GetScripts(): $CancellablePromise<db$0.ScriptBasicRow[] | null> {
    return $Call.ByID(239759242);
}

export function GetTextureResizeSettings(): $CancellablePromise<$models.TextureResizeSettings> {
    return $Call.ByID(250822864);
}

export function GetTextureResizeState(): $CancellablePromise<$models.TextureResizeProgressEvent> {
    return $Call.ByID(2436127182);
}

export function GetTextureUpscaleRuntimeStatus(): $CancellablePromise<$models.TextureUpscaleRuntimeStatuses> {
    return $Call.ByID(86882648);
}

export function IsPythonAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(2556967675);
}

export function ListTextureFolder(
    targetPath: string,
    patch: $models.TextureResizeSettingsPatch | null,
): $CancellablePromise<$models.TextureResizeListItem[] | null> {
    return $Call.ByID(1244278657, targetPath, patch);
}

export function ListTextureMod(
    modPath: string,
    patch: $models.TextureResizeSettingsPatch | null,
): $CancellablePromise<$models.TextureResizeListItem[] | null> {
    return $Call.ByID(3694015823, modPath, patch);
}

export function LoadModViewer(modPath: string): $CancellablePromise<$models.ModelViewerTransport> {
    return $Call.ByID(1697165908, modPath);
}

export function PersistModelViewerToggleState(
    iniPath: string,
    state: { [_ in string]?: any } | null,
): $CancellablePromise<$models.PersistModelViewerResult> {
    return $Call.ByID(3706860710, iniPath, state);
}

export function ResizeTextureFile(
    input: $models.TextureResizeFileRunInput,
): $CancellablePromise<$models.TextureResizeResult> {
    return $Call.ByID(3438396943, input);
}

export function ResizeTextureFolder(
    input: $models.TextureResizeRunInput,
): $CancellablePromise<$models.TextureResizeResult> {
    return $Call.ByID(79919977, input);
}

export function ResizeTextureMod(
    modPath: string,
    input: $models.TextureResizeModInput,
): $CancellablePromise<$models.TextureResizeResult> {
    return $Call.ByID(1979455463, modPath, input);
}

export function RunPreset(presetID: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(3811670628, presetID, destPath);
}

export function RunScript(scriptID: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(699525636, scriptID, destPath);
}

export function SaveScript(inputPath: string): $CancellablePromise<void> {
    return $Call.ByID(3210775832, inputPath);
}

export function SaveTextureResizeSettings(
    patch: $models.TextureResizeSettingsPatch,
): $CancellablePromise<$models.TextureResizeSettings> {
    return $Call.ByID(531489863, patch);
}

export function SendInput(input: string): $CancellablePromise<boolean> {
    return $Call.ByID(3243520276, input);
}

export function StartPersistWatcher(): $CancellablePromise<void> {
    return $Call.ByID(4010887266);
}

export function StopPersistWatcher(): $CancellablePromise<boolean> {
    return $Call.ByID(2541884354);
}

export function ToggleViewerApplyHotkeyToArtifacts(hotkey: string): $CancellablePromise<void> {
    return $Call.ByID(3638619746, hotkey);
}

export function ToggleViewerCancelCurrentWork(): $CancellablePromise<boolean> {
    return $Call.ByID(1032679718);
}

export function ToggleViewerGetLogs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3449462439);
}

export function ToggleViewerGetState(): $CancellablePromise<$models.ToggleViewerState> {
    return $Call.ByID(2919864401);
}

export function ToggleViewerRunBatchDelete(): $CancellablePromise<void> {
    return $Call.ByID(3355710408);
}

export function ToggleViewerRunBatchGenerate(): $CancellablePromise<void> {
    return $Call.ByID(68751508);
}

export function TouchProfileAnalyzeComponents(
    input: $models.TouchProfileAnalyzeInput,
): $CancellablePromise<$models.TouchDraft> {
    return $Call.ByID(3768512858, input);
}

export function TouchProfileApply(
    input: $models.TouchProfileApplyInput,
): $CancellablePromise<$models.TouchApplyResult> {
    return $Call.ByID(2522548966, input);
}

export function TouchProfileDiscardDraft(
    sessionID: string,
): $CancellablePromise<$models.TouchProfileOK> {
    return $Call.ByID(978483691, sessionID);
}

export function TouchProfileGetMeshPreview(
    input: $models.TouchProfilePreviewInput,
): $CancellablePromise<$models.TouchMeshPreview> {
    return $Call.ByID(3797038149, input);
}

export function TouchProfileGetPreview(
    input: $models.TouchProfilePreviewInput,
): $CancellablePromise<$models.TouchProfilePreview> {
    return $Call.ByID(3459824038, input);
}

export function TouchProfilePrepare(
    input: $models.TouchProfileLoadInput,
): $CancellablePromise<$models.TouchModInspection> {
    return $Call.ByID(3680234253, input);
}

export function TouchProfileRegenerate(
    input: $models.TouchProfileApplyInput,
): $CancellablePromise<$models.TouchApplyResult> {
    return $Call.ByID(1070203548, input);
}

export function TouchProfileRollback(
    input: $models.TouchProfileRollbackInput,
): $CancellablePromise<$models.TouchRollbackResult> {
    return $Call.ByID(4123278206, input);
}

export function TouchProfileSaveDraft(
    draft: $models.TouchDraft,
): $CancellablePromise<$models.TouchDraft> {
    return $Call.ByID(369165078, draft);
}

export function TouchProfileUpdateZoneSettings(
    input: $models.TouchProfileUpdateZoneSettingsInput,
): $CancellablePromise<$models.TouchDraft> {
    return $Call.ByID(3239307272, input);
}

export function WuwaFixerCleanBackups(modPath: string): $CancellablePromise<void> {
    return $Call.ByID(229947354, modPath);
}

export function WuwaFixerGetBackupSize(
    modPath: string,
): $CancellablePromise<$models.WuwaBackupSize> {
    return $Call.ByID(711291729, modPath);
}

export function WuwaFixerGetRateStatus(): $CancellablePromise<$models.GitHubRateState | null> {
    return $Call.ByID(1426455902);
}

export function WuwaFixerGetStatus(
    importer: string | null,
): $CancellablePromise<$models.WuwaFixerStatus> {
    return $Call.ByID(4119647800, importer);
}

export function WuwaFixerInstallOrUpdate(): $CancellablePromise<$models.WuwaFixerStatus> {
    return $Call.ByID(891250321);
}

export function WuwaFixerPrepareRun(
    importer: string | null,
): $CancellablePromise<$models.WuwaFixerPrepareResult> {
    return $Call.ByID(4091984094, importer);
}

export function WuwaFixerRollbackToGroup(
    modPath: string,
    groupKey: string,
): $CancellablePromise<void> {
    return $Call.ByID(2256339182, modPath, groupKey);
}

export function WuwaFixerRun(
    modPath: string,
    options: $models.WuwaFixerOptions,
): $CancellablePromise<void> {
    return $Call.ByID(667324571, modPath, options);
}

export function WuwaFixerScanBackups(
    modPath: string,
): $CancellablePromise<$models.WuwaBackupGroup[] | null> {
    return $Call.ByID(1250536594, modPath);
}
