/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as XxmiRouteRouteImport } from './routes/xxmi/route'
import { Route as SettingRouteRouteImport } from './routes/setting/route'
import { Route as BackupRouteRouteImport } from './routes/backup/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModIndexRouteImport } from './routes/mod/index'
import { Route as BackupIndexRouteImport } from './routes/backup/index'
import { Route as XxmiGimiRouteImport } from './routes/xxmi/gimi'
import { Route as SettingSyncRouteImport } from './routes/setting/sync'
import { Route as SettingSpaceRouteImport } from './routes/setting/space'
import { Route as SettingNotiRouteImport } from './routes/setting/noti'
import { Route as SettingNetRouteImport } from './routes/setting/net'
import { Route as SettingModRouteImport } from './routes/setting/mod'
import { Route as SettingGenRouteImport } from './routes/setting/gen'
import { Route as SettingBakRouteImport } from './routes/setting/bak'
import { Route as SettingAccRouteImport } from './routes/setting/acc'
import { Route as DriveShareIdRouteImport } from './routes/drive/share.$id'
import { Route as DriveDriveIdRouteImport } from './routes/drive/drive.$id'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const XxmiRouteRoute = XxmiRouteRouteImport.update({
  id: '/xxmi',
  path: '/xxmi',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRouteRoute = SettingRouteRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRouteRoute = BackupRouteRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModIndexRoute = ModIndexRouteImport.update({
  id: '/mod/',
  path: '/mod/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupIndexRoute = BackupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackupRouteRoute,
} as any)
const XxmiGimiRoute = XxmiGimiRouteImport.update({
  id: '/gimi',
  path: '/gimi',
  getParentRoute: () => XxmiRouteRoute,
} as any)
const SettingSyncRoute = SettingSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingSpaceRoute = SettingSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingNotiRoute = SettingNotiRouteImport.update({
  id: '/noti',
  path: '/noti',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingNetRoute = SettingNetRouteImport.update({
  id: '/net',
  path: '/net',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingModRoute = SettingModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingGenRoute = SettingGenRouteImport.update({
  id: '/gen',
  path: '/gen',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingBakRoute = SettingBakRouteImport.update({
  id: '/bak',
  path: '/bak',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingAccRoute = SettingAccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => SettingRouteRoute,
} as any)
const DriveShareIdRoute = DriveShareIdRouteImport.update({
  id: '/drive/share/$id',
  path: '/drive/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveDriveIdRoute = DriveDriveIdRouteImport.update({
  id: '/drive/drive/$id',
  path: '/drive/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/xxmi': typeof XxmiRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/report': typeof ReportRoute
  '/transfer': typeof TransferRoute
  '/setting/acc': typeof SettingAccRoute
  '/setting/bak': typeof SettingBakRoute
  '/setting/gen': typeof SettingGenRoute
  '/setting/mod': typeof SettingModRoute
  '/setting/net': typeof SettingNetRoute
  '/setting/noti': typeof SettingNotiRoute
  '/setting/space': typeof SettingSpaceRoute
  '/setting/sync': typeof SettingSyncRoute
  '/xxmi/gimi': typeof XxmiGimiRoute
  '/backup/': typeof BackupIndexRoute
  '/mod/': typeof ModIndexRoute
  '/drive/drive/$id': typeof DriveDriveIdRoute
  '/drive/share/$id': typeof DriveShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteRouteWithChildren
  '/xxmi': typeof XxmiRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/report': typeof ReportRoute
  '/transfer': typeof TransferRoute
  '/setting/acc': typeof SettingAccRoute
  '/setting/bak': typeof SettingBakRoute
  '/setting/gen': typeof SettingGenRoute
  '/setting/mod': typeof SettingModRoute
  '/setting/net': typeof SettingNetRoute
  '/setting/noti': typeof SettingNotiRoute
  '/setting/space': typeof SettingSpaceRoute
  '/setting/sync': typeof SettingSyncRoute
  '/xxmi/gimi': typeof XxmiGimiRoute
  '/backup': typeof BackupIndexRoute
  '/mod': typeof ModIndexRoute
  '/drive/drive/$id': typeof DriveDriveIdRoute
  '/drive/share/$id': typeof DriveShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/xxmi': typeof XxmiRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/report': typeof ReportRoute
  '/transfer': typeof TransferRoute
  '/setting/acc': typeof SettingAccRoute
  '/setting/bak': typeof SettingBakRoute
  '/setting/gen': typeof SettingGenRoute
  '/setting/mod': typeof SettingModRoute
  '/setting/net': typeof SettingNetRoute
  '/setting/noti': typeof SettingNotiRoute
  '/setting/space': typeof SettingSpaceRoute
  '/setting/sync': typeof SettingSyncRoute
  '/xxmi/gimi': typeof XxmiGimiRoute
  '/backup/': typeof BackupIndexRoute
  '/mod/': typeof ModIndexRoute
  '/drive/drive/$id': typeof DriveDriveIdRoute
  '/drive/share/$id': typeof DriveShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/setting'
    | '/xxmi'
    | '/auth'
    | '/report'
    | '/transfer'
    | '/setting/acc'
    | '/setting/bak'
    | '/setting/gen'
    | '/setting/mod'
    | '/setting/net'
    | '/setting/noti'
    | '/setting/space'
    | '/setting/sync'
    | '/xxmi/gimi'
    | '/backup/'
    | '/mod/'
    | '/drive/drive/$id'
    | '/drive/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setting'
    | '/xxmi'
    | '/auth'
    | '/report'
    | '/transfer'
    | '/setting/acc'
    | '/setting/bak'
    | '/setting/gen'
    | '/setting/mod'
    | '/setting/net'
    | '/setting/noti'
    | '/setting/space'
    | '/setting/sync'
    | '/xxmi/gimi'
    | '/backup'
    | '/mod'
    | '/drive/drive/$id'
    | '/drive/share/$id'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/setting'
    | '/xxmi'
    | '/auth'
    | '/report'
    | '/transfer'
    | '/setting/acc'
    | '/setting/bak'
    | '/setting/gen'
    | '/setting/mod'
    | '/setting/net'
    | '/setting/noti'
    | '/setting/space'
    | '/setting/sync'
    | '/xxmi/gimi'
    | '/backup/'
    | '/mod/'
    | '/drive/drive/$id'
    | '/drive/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRouteRoute: typeof BackupRouteRouteWithChildren
  SettingRouteRoute: typeof SettingRouteRouteWithChildren
  XxmiRouteRoute: typeof XxmiRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReportRoute: typeof ReportRoute
  TransferRoute: typeof TransferRoute
  ModIndexRoute: typeof ModIndexRoute
  DriveDriveIdRoute: typeof DriveDriveIdRoute
  DriveShareIdRoute: typeof DriveShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xxmi': {
      id: '/xxmi'
      path: '/xxmi'
      fullPath: '/xxmi'
      preLoaderRoute: typeof XxmiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/': {
      id: '/mod/'
      path: '/mod'
      fullPath: '/mod/'
      preLoaderRoute: typeof ModIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/': {
      id: '/backup/'
      path: '/'
      fullPath: '/backup/'
      preLoaderRoute: typeof BackupIndexRouteImport
      parentRoute: typeof BackupRouteRoute
    }
    '/xxmi/gimi': {
      id: '/xxmi/gimi'
      path: '/gimi'
      fullPath: '/xxmi/gimi'
      preLoaderRoute: typeof XxmiGimiRouteImport
      parentRoute: typeof XxmiRouteRoute
    }
    '/setting/sync': {
      id: '/setting/sync'
      path: '/sync'
      fullPath: '/setting/sync'
      preLoaderRoute: typeof SettingSyncRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/space': {
      id: '/setting/space'
      path: '/space'
      fullPath: '/setting/space'
      preLoaderRoute: typeof SettingSpaceRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/noti': {
      id: '/setting/noti'
      path: '/noti'
      fullPath: '/setting/noti'
      preLoaderRoute: typeof SettingNotiRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/net': {
      id: '/setting/net'
      path: '/net'
      fullPath: '/setting/net'
      preLoaderRoute: typeof SettingNetRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/mod': {
      id: '/setting/mod'
      path: '/mod'
      fullPath: '/setting/mod'
      preLoaderRoute: typeof SettingModRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/gen': {
      id: '/setting/gen'
      path: '/gen'
      fullPath: '/setting/gen'
      preLoaderRoute: typeof SettingGenRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/bak': {
      id: '/setting/bak'
      path: '/bak'
      fullPath: '/setting/bak'
      preLoaderRoute: typeof SettingBakRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/acc': {
      id: '/setting/acc'
      path: '/acc'
      fullPath: '/setting/acc'
      preLoaderRoute: typeof SettingAccRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/drive/share/$id': {
      id: '/drive/share/$id'
      path: '/drive/share/$id'
      fullPath: '/drive/share/$id'
      preLoaderRoute: typeof DriveShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/drive/$id': {
      id: '/drive/drive/$id'
      path: '/drive/drive/$id'
      fullPath: '/drive/drive/$id'
      preLoaderRoute: typeof DriveDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackupRouteRouteChildren {
  BackupIndexRoute: typeof BackupIndexRoute
}

const BackupRouteRouteChildren: BackupRouteRouteChildren = {
  BackupIndexRoute: BackupIndexRoute,
}

const BackupRouteRouteWithChildren = BackupRouteRoute._addFileChildren(
  BackupRouteRouteChildren,
)

interface SettingRouteRouteChildren {
  SettingAccRoute: typeof SettingAccRoute
  SettingBakRoute: typeof SettingBakRoute
  SettingGenRoute: typeof SettingGenRoute
  SettingModRoute: typeof SettingModRoute
  SettingNetRoute: typeof SettingNetRoute
  SettingNotiRoute: typeof SettingNotiRoute
  SettingSpaceRoute: typeof SettingSpaceRoute
  SettingSyncRoute: typeof SettingSyncRoute
}

const SettingRouteRouteChildren: SettingRouteRouteChildren = {
  SettingAccRoute: SettingAccRoute,
  SettingBakRoute: SettingBakRoute,
  SettingGenRoute: SettingGenRoute,
  SettingModRoute: SettingModRoute,
  SettingNetRoute: SettingNetRoute,
  SettingNotiRoute: SettingNotiRoute,
  SettingSpaceRoute: SettingSpaceRoute,
  SettingSyncRoute: SettingSyncRoute,
}

const SettingRouteRouteWithChildren = SettingRouteRoute._addFileChildren(
  SettingRouteRouteChildren,
)

interface XxmiRouteRouteChildren {
  XxmiGimiRoute: typeof XxmiGimiRoute
}

const XxmiRouteRouteChildren: XxmiRouteRouteChildren = {
  XxmiGimiRoute: XxmiGimiRoute,
}

const XxmiRouteRouteWithChildren = XxmiRouteRoute._addFileChildren(
  XxmiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRouteRoute: BackupRouteRouteWithChildren,
  SettingRouteRoute: SettingRouteRouteWithChildren,
  XxmiRouteRoute: XxmiRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReportRoute: ReportRoute,
  TransferRoute: TransferRoute,
  ModIndexRoute: ModIndexRoute,
  DriveDriveIdRoute: DriveDriveIdRoute,
  DriveShareIdRoute: DriveShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
