// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Directory {
    id: string;
    parentId: string | null;
    name: string;
}

export interface DownloadFile {
    id: string;
    fileId: string;
    parentId: string | null;
    name: string;
    size: number;
    uncompSize?: number | null;
    compAlg: string | null;
    url: string;
    urlOrigin?: string;
}

export enum PlanPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanPermissionCheck = "permission_check",
    PlanParentLookup = "parent_lookup",
    PlanFileValidation = "file_validation",
    PlanDedupLookup = "dedup_lookup",
    PlanProcessing = "processing",
}

export interface Root {
    id: string;
    parentId: string | null;
    name: string;
}

/**
 * Snapshot is the renderer-safe transfer shape. The payload Data and runner
 * state are deliberately absent, matching Electron's getDisplayTransfers.
 */
export interface Snapshot {
    pid: string;
    type: string;
    queueGroupId?: number | null;
    currentId?: string;
    status: Status;
    totalSize: number;
    transferedSize: number;
    progress: number;
    speed: number;
    eta: number;
    startTime: number;
    name: string;
    totalFiles: number;
    transferedFiles: number;
    failedFiles: number;
    path?: string;
    error?: string;
    errorCode?: string;
    planPhase?: PlanPhase | null;
    planProgress?: number | null;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusPreparing = "preparing",
    StatusProgress = "progress",
    StatusCompleted = "completed",
    StatusPaused = "paused",
    StatusCanceled = "canceled",
    StatusError = "error",
}
