// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(pid: string): $CancellablePromise<void> {
    return $Call.ByID(1211276706, pid);
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(56664501);
}

/**
 * List returns newest-first renderer-safe snapshots.
 */
export function List(): $CancellablePromise<$models.Snapshot[] | null> {
    return $Call.ByID(2477530864);
}

export function Pause(pid: string): $CancellablePromise<void> {
    return $Call.ByID(309189418, pid);
}

export function PauseAll(): $CancellablePromise<void> {
    return $Call.ByID(3991742353);
}

export function Resume(pid: string): $CancellablePromise<void> {
    return $Call.ByID(3833279403, pid);
}

export function ResumeAll(): $CancellablePromise<void> {
    return $Call.ByID(20185646);
}

export function Retry(pid: string): $CancellablePromise<void> {
    return $Call.ByID(1364063946, pid);
}
