/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface FolderGroup {
  name: string
  path: string
  mods: Array<ModInfo>
  preview?: string
  modCount: number
}

export declare function getCharactersFolder(modFolderPath: string, fallbackToModPreview?: boolean | undefined | null): Promise<Array<FolderGroup>>

export declare function getMods(groupPath: string): Promise<FolderGroup>

export interface IniResult {
  name: string
  path: string
  toggleKeys: Array<ToggleKey>
  hasToggleKey: boolean
}

export interface ModInfo {
  name: string
  path: string
  isEnabled: boolean
  preview?: string
  mtime: number
  size: number
  inis: Array<IniResult>
}

export declare function processIniFiles(paths: Array<string>): Promise<Array<IniResult>>

export declare function sendF10(pid: number): Promise<boolean>

export interface ToggleKey {
  sectionName: string
  iniFileName: string
  key?: string
  back?: string
  type?: string
  variable: string
  values: Array<string>
  currentValue?: string
}
