// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Log is the Wails-facing logger. It is a small stdlib port of the Electron
 * logger's level filter and JSON line shape, not a pino clone.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Log(level: string, msg: any, where: string): $CancellablePromise<void> {
    return $Call.ByID(868151832, level, msg, where);
}
