// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CleanupModelViewerMemorySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1406312932, sessionID);
}

export function CreateModelViewerMemorySession(): $CancellablePromise<string> {
    return $Call.ByID(3663487100);
}

export function LocalFileURL(path: string, original: boolean): $CancellablePromise<string> {
    return $Call.ByID(3881729970, path, original);
}

export function WriteModelViewerMemoryBuffer(sessionID: string, bufferID: string, data: string | null, contentType: string): $CancellablePromise<string> {
    return $Call.ByID(2383294267, sessionID, bufferID, data, contentType);
}
