// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(userInitiated: boolean): $CancellablePromise<void> {
    return $Call.ByID(1397318578, userInitiated);
}

export function DismissUpdateDialog(): $CancellablePromise<void> {
    return $Call.ByID(3923784044);
}

export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2623459178);
}

export function GetStatus(): $CancellablePromise<$models.UpdaterStatus> {
    return $Call.ByID(3362057563);
}

export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3168596751);
}
