export {
    applySnorm8VectorCorrection,
    assertFinitePositions,
    detectSnorm8VectorLayout,
    encodeFloat32Le,
    extractPositions,
    POSITION_STRIDE_FLOAT3,
    validatePositionBuffer,
    writePositionsIntoBuffer,
    type LayoutValidationError,
    type PositionLayoutValidation,
} from "./buffer";
export {
    anisotropicScaleFromOriginal,
    computeBoundingCenter,
    computeVertexNormals,
    computeWeightedPivot,
    correctSnorm8TangentNormal,
    displacementMetrics,
    effectiveScaleFactors,
    recalculateNormalsAndTangents,
} from "./deform";

export {
    BLEND_INDICES_OFFSET,
    BLEND_INFLUENCE_COUNT,
    BLEND_WEIGHTS_OFFSET,
    DEFAULT_BLEND_STRIDE,
    EFMI_BLEND_STRIDE,
    EFMI_INDICES_OFFSET,
    MIHOYO_BLEND_STRIDE,
    MIHOYO_INDICES_OFFSET,
    MIHOYO_WEIGHTS_OFFSET,
    EFMI_RIGID_STRIDE,
    EFMI_WEIGHTS_OFFSET,
    extractBoneWeights,
    influencesAtVertex,
    listBlendBones,
    parseBlendBuffer,
    rankBonesAtVertices,
    validateBlendBuffer,
    type BlendBoneInfo,
    type ParsedBlendBuffer,
} from "./blend";
export {
    applyMultiRegionDeform,
    BODY_REGION_IDS,
    composeDisplayWeights,
    composeDisplayWeightsInto,
    composeEffectiveScales,
    computeMeshBounds,
    computeRegionPivot,
    evaluateShapeLayers,
    generateRegionWeights,
    REGION_PRESETS,
    type ActiveRegionDeform,
    type BodyRegionId,
    type DeformMetrics,
    type MeshBounds,
    type RegionPreset,
    type SelectionMask,
    type ShapeLayer,
} from "./regions";

export {
    applyBrushStroke,
    brushFalloff,
    clamp01,
    eraseVertex,
    mirrorWeightsAcrossX,
    paintVertex,
    weightToRgb,
    weightToRgbInto,
    writeWeightColors,
    type BrushMode,
} from "./weights";
export {
    applyGeodesicBrush,
    adjacencyVertexCount,
    buildConnectedComponents,
    buildSymmetryMap,
    buildVertexAdjacency,
    createGeodesicBrushWorkspace,
    growSelectionWeights,
    mirrorWeightsWithCache,
    selectConnectedComponent,
    shrinkSelectionWeights,
    smoothSelectionWeights,
    type GeodesicBrushWorkspace,
    type VertexAdjacency,
} from "./selection";
