package agent

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"nahida.live/desktop/internal/db"
)

func TestNormalizeSessionTitle(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		raw  string
		want string
	}{
		{name: "plain", raw: "Broken mod textures", want: "Broken mod textures"},
		{
			name: "reasoning block",
			raw:  "<think>weighing options</think>\nBroken mod textures",
			want: "Broken mod textures",
		},
		{
			name: "unterminated reasoning block",
			raw:  "Broken mod textures\n<think>never closed",
			want: "Broken mod textures",
		},
		{name: "quoted", raw: `"Broken mod textures"`, want: "Broken mod textures"},
		{name: "bold", raw: "**Broken mod textures**", want: "Broken mod textures"},
		{name: "heading", raw: "## Broken mod textures", want: "Broken mod textures"},
		{name: "labelled", raw: "Title: Broken mod textures", want: "Broken mod textures"},
		{name: "first filled line", raw: "\n\nBroken mod textures\nGenerated by a model", want: "Broken mod textures"},
		{name: "collapsed whitespace", raw: "Broken   mod\ttextures", want: "Broken mod textures"},
		{name: "empty", raw: " \n\t ", want: ""},
		{name: "truncated", raw: strings.Repeat("a", 60), want: strings.Repeat("a", sessionTitleRunes) + "…"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := normalizeSessionTitle(test.raw); got != test.want {
				t.Fatalf("normalizeSessionTitle(%q) = %q, want %q", test.raw, got, test.want)
			}
		})
	}
}

func TestSessionTitleRequestSummarizesTheRequest(t *testing.T) {
	t.Parallel()
	ctx := t.Context()
	requests := make(chan map[string]any, 1)
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(request.Body).Decode(&body); err != nil {
			t.Errorf("decode provider request: %v", err)
			return
		}
		requests <- body
		writeAssistantText(response, "<think>weighing options</think>\nBroken mod textures")
	}))
	defer server.Close()

	sink := newTitleEventSink()
	service := newSettingsService(t, Options{HTTP: server.Client(), EventEmit: sink.emit})
	client, err := service.dbClient()
	if err != nil {
		t.Fatal(err)
	}
	question := "이 모드 텍스처가 깨져 보여. 원인을 찾아줘."
	fallback := messageTitle(question, nil)
	sessionID := insertTitleSession(t, client, fallback)

	service.summarizeSessionTitle(ctx, newTitleAdapter(server), sessionID, "run", fallback, question)

	body := nextTitleRequest(t, requests)
	if body["reasoning_effort"] != "low" {
		t.Fatalf("reasoning_effort = %#v", body["reasoning_effort"])
	}
	if tools, _ := body["tools"].([]any); len(tools) != 0 {
		t.Fatalf("title request carried tools: %#v", tools)
	}
	messages, _ := body["messages"].([]any)
	if len(messages) != 2 {
		t.Fatalf("title request messages = %#v", messages)
	}
	if system := messages[0].(map[string]any); system["content"] != sessionTitlePrompt {
		t.Fatalf("system prompt = %#v", system["content"])
	}
	if prompt, _ := messages[1].(map[string]any)["content"].(string); !strings.Contains(prompt, question) {
		t.Fatalf("user prompt = %q", prompt)
	}

	row, err := client.AgentSessions.Get(ctx, sessionID)
	if err != nil || row.Title != "Broken mod textures" {
		t.Fatalf("stored title = %#v, %v", row, err)
	}
	event := sink.wait(t)
	payload, _ := event.Payload.(map[string]any)
	if event.SessionID != sessionID || payload["title"] != "Broken mod textures" {
		t.Fatalf("session-title event = %#v", event)
	}
}

func TestSessionTitleRetriesWithoutReasoningEffort(t *testing.T) {
	t.Parallel()
	ctx := t.Context()
	requests := make(chan map[string]any, 2)
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(request.Body).Decode(&body); err != nil {
			t.Errorf("decode provider request: %v", err)
			return
		}
		requests <- body
		if _, present := body["reasoning_effort"]; present {
			response.WriteHeader(http.StatusBadRequest)
			_, _ = response.Write([]byte(`{"error":{"message":"unknown field reasoning_effort"}}`))
			return
		}
		writeAssistantText(response, "Broken mod textures")
	}))
	defer server.Close()

	service := newSettingsService(t, Options{HTTP: server.Client()})
	client, err := service.dbClient()
	if err != nil {
		t.Fatal(err)
	}
	sessionID := insertTitleSession(t, client, "first message")
	service.summarizeSessionTitle(
		ctx,
		newTitleAdapter(server),
		sessionID,
		"run",
		"first message",
		"why are my textures broken",
	)

	first := nextTitleRequest(t, requests)
	if first["reasoning_effort"] != "low" {
		t.Fatalf("first attempt reasoning_effort = %#v", first["reasoning_effort"])
	}
	second := nextTitleRequest(t, requests)
	if _, present := second["reasoning_effort"]; present {
		t.Fatalf("retry kept reasoning_effort: %#v", second)
	}
	row, err := client.AgentSessions.Get(ctx, sessionID)
	if err != nil || row.Title != "Broken mod textures" {
		t.Fatalf("stored title = %#v, %v", row, err)
	}
}

func TestSessionTitleKeepsFallbackWhenTheProviderFails(t *testing.T) {
	t.Parallel()
	ctx := t.Context()
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, _ *http.Request) {
		response.WriteHeader(http.StatusInternalServerError)
		_, _ = response.Write([]byte(`{"error":{"message":"provider is down"}}`))
	}))
	defer server.Close()

	sink := newTitleEventSink()
	service := newSettingsService(t, Options{HTTP: server.Client(), EventEmit: sink.emit})
	client, err := service.dbClient()
	if err != nil {
		t.Fatal(err)
	}
	sessionID := insertTitleSession(t, client, "first message")
	service.summarizeSessionTitle(
		ctx,
		newTitleAdapter(server),
		sessionID,
		"run",
		"first message",
		"why are my textures broken",
	)

	row, err := client.AgentSessions.Get(ctx, sessionID)
	if err != nil || row.Title != "first message" {
		t.Fatalf("stored title = %#v, %v", row, err)
	}
	sink.empty(t)
}

func TestSessionTitleKeepsAUserRename(t *testing.T) {
	t.Parallel()
	ctx := t.Context()
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, _ *http.Request) {
		writeAssistantText(response, "Broken mod textures")
	}))
	defer server.Close()

	sink := newTitleEventSink()
	service := newSettingsService(t, Options{HTTP: server.Client(), EventEmit: sink.emit})
	client, err := service.dbClient()
	if err != nil {
		t.Fatal(err)
	}
	sessionID := insertTitleSession(t, client, "Renamed by the user")
	service.summarizeSessionTitle(
		ctx,
		newTitleAdapter(server),
		sessionID,
		"run",
		"first message",
		"why are my textures broken",
	)

	row, err := client.AgentSessions.Get(ctx, sessionID)
	if err != nil || row.Title != "Renamed by the user" {
		t.Fatalf("stored title = %#v, %v", row, err)
	}
	sink.empty(t)
}

func TestSendGeneratesASessionSummaryTitle(t *testing.T) {
	t.Parallel()
	ctx := t.Context()
	server := httptest.NewServer(http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(request.Body).Decode(&body); err != nil {
			t.Errorf("decode provider request: %v", err)
			return
		}
		if isTitleRequest(body) {
			writeAssistantText(response, "Broken mod texture diagnosis")
			return
		}
		writeAssistantText(response, "Looking into it.")
	}))
	defer server.Close()

	sink := newTitleEventSink()
	service, _ := newImageSessionService(t, Options{HTTP: server.Client(), EventEmit: sink.emit})
	input := headerSettingsInput(nil)
	input.Endpoint = server.URL
	if _, err := service.UpdateSettings(ctx, input); err != nil {
		t.Fatal(err)
	}
	session, err := service.CreateSession(ctx, AgentScope{Type: "global"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := service.Send(ctx, session.ID, "이 모드 텍스처가 깨져 보여. 원인을 찾아줘.", nil); err != nil {
		t.Fatal(err)
	}
	client, err := service.dbClient()
	if err != nil {
		t.Fatal(err)
	}

	waitForSessionTitle(t, client, session.ID, "Broken mod texture diagnosis")
	if event := sink.wait(t); event.SessionID != session.ID {
		t.Fatalf("session-title event = %#v", event)
	}
}

// newTitleAdapter points an adapter at one test provider.
func newTitleAdapter(server *httptest.Server) ModelAdapter {
	return newModelAdapter(
		modelAdapterConfig{
			settings: AgentSettingsView{Protocol: "openai-compatible", Endpoint: server.URL, Model: "test-model"},
		},
		server.Client(),
	)
}

func insertTitleSession(t *testing.T, client *db.Client, title string) string {
	t.Helper()
	row := db.AgentSessionRow{ID: "session", ScopeType: "global", Title: title, CreatedAt: "1", UpdatedAt: "1"}
	if err := client.AgentSessions.Insert(t.Context(), row); err != nil {
		t.Fatal(err)
	}
	return row.ID
}

// writeAssistantText answers a streaming chat completions request with one text delta.
func writeAssistantText(response http.ResponseWriter, text string) {
	escaped := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", "").Replace(text)
	response.Header().Set("Content-Type", "text/event-stream")
	_, _ = fmt.Fprintf(
		response,
		"data: {\"choices\":[{\"delta\":{\"content\":\"%s\"}}]}\n\ndata: [DONE]\n\n",
		escaped,
	)
}

func isTitleRequest(body map[string]any) bool {
	messages, _ := body["messages"].([]any)
	if len(messages) == 0 {
		return false
	}
	system, _ := messages[0].(map[string]any)
	return system["content"] == sessionTitlePrompt
}

func nextTitleRequest(t *testing.T, requests <-chan map[string]any) map[string]any {
	t.Helper()
	select {
	case body := <-requests:
		return body
	case <-time.After(5 * time.Second):
		t.Fatal("provider request was not received")
		return nil
	}
}

func waitForSessionTitle(t *testing.T, client *db.Client, sessionID, want string) {
	t.Helper()
	ctx := t.Context()
	deadline := time.Now().Add(10 * time.Second)
	stored := ""
	for time.Now().Before(deadline) {
		row, err := client.AgentSessions.Get(ctx, sessionID)
		if err != nil {
			t.Fatal(err)
		}
		if row != nil {
			stored = row.Title
			if stored == want {
				return
			}
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatalf("session title = %q, want %q", stored, want)
}

// titleEventSink captures the session-title stream events of one service.
type titleEventSink struct {
	events chan AgentStreamEvent
}

func newTitleEventSink() *titleEventSink {
	return &titleEventSink{events: make(chan AgentStreamEvent, 8)}
}

func (s *titleEventSink) emit(name string, payload ...any) {
	if name != "agent:update" || len(payload) != 1 {
		return
	}
	event, ok := payload[0].(AgentStreamEvent)
	if !ok || event.Type != "session-title" {
		return
	}
	select {
	case s.events <- event:
	default:
	}
}

func (s *titleEventSink) wait(t *testing.T) AgentStreamEvent {
	t.Helper()
	select {
	case event := <-s.events:
		return event
	case <-time.After(5 * time.Second):
		t.Fatal("no session-title event was emitted")
		return AgentStreamEvent{}
	}
}

func (s *titleEventSink) empty(t *testing.T) {
	t.Helper()
	select {
	case event := <-s.events:
		t.Fatalf("unexpected session-title event: %#v", event)
	case <-time.After(50 * time.Millisecond):
	}
}
