// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function OpenSetting(): $CancellablePromise<void> {
    return $Call.ByID(135820675);
}

/**
 * SyncRoute keeps the SPA route available when the native window must be
 * recreated to change WebView devtools availability.
 */
export function SyncRoute(route: string): $CancellablePromise<void> {
    return $Call.ByID(1523567223, route);
}

/**
 * SyncTitleBarOverlay is retained for renderer API compatibility. The main
 * window is frameless, so Electron's title-bar overlay has no equivalent.
 */
export function SyncTitleBarOverlay(
    $0: $models.TitleBarOverlaySyncOptions,
): $CancellablePromise<void> {
    return $Call.ByID(3837297467, $0);
}
