// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ResolveDirectoryConflict displays Electron's overwrite/new-name/cancel
 * prompt for a directory download.
 */
export function ResolveDirectoryConflict(
    opts: $models.DirectoryConflictOptions,
): $CancellablePromise<$models.DirectoryConflictChoice> {
    return $Call.ByID(192642464, opts);
}

export function SaveFile(opts: $models.SaveFileOptions): $CancellablePromise<$models.DialogResult> {
    return $Call.ByID(566408398, opts);
}

export function SelectDirectory(): $CancellablePromise<$models.DialogResult> {
    return $Call.ByID(3899949952);
}

export function ShowModal(opts: $models.ModalOptions): $CancellablePromise<$models.ModalResult> {
    return $Call.ByID(3599164605, opts);
}

export function ShowOpenDialog(
    opts: $models.OpenDialogOptions,
): $CancellablePromise<$models.OpenDialogResult> {
    return $Call.ByID(4196456780, opts);
}
