// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AssertValidWindowsFilename(name: string): $CancellablePromise<void> {
    return $Call.ByID(651699460, name);
}

export function FormatProcessList(
    processes: $models.ProcessInfo[] | null,
): $CancellablePromise<string> {
    return $Call.ByID(1906698512, processes);
}

/**
 * GetFileWriteAccess is the detailed writable path from Electron FS.
 */
export function GetFileWriteAccess(
    filePath: string,
    parentPath: string,
): $CancellablePromise<$models.FileWriteAccessResult> {
    return $Call.ByID(732555467, filePath, parentPath);
}

export function GetPathMetadata(pathStr: string): $CancellablePromise<$models.PathMetadata> {
    return $Call.ByID(3368348406, pathStr);
}

export function GetUniqueName(
    name: string,
    existingNames: string[] | null,
): $CancellablePromise<string> {
    return $Call.ByID(1284205592, name, existingNames);
}

export function IsPathWritable(pathStr: string): $CancellablePromise<boolean> {
    return $Call.ByID(3953856159, pathStr);
}

export function IsValidWindowsFilename(name: string): $CancellablePromise<boolean> {
    return $Call.ByID(4215094202, name);
}

/**
 * Mkdir creates parentPath/name. It is mkdir, not MkdirAll.
 */
export function Mkdir(parentPath: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2969596635, parentPath, name);
}

export function SanitizePath(input: string): $CancellablePromise<string> {
    return $Call.ByID(2515133264, input);
}

export function SanitizeWindowsFilename(
    input: string,
    sanitizeString: string,
): $CancellablePromise<string> {
    return $Call.ByID(3363453569, input, sanitizeString);
}
