// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppStatus is the Electron util:getAppStatus payload.
 */
export interface AppStatus {
    version: string;
    isPackaged: boolean;
    isDev: boolean;
    platform: string;
}

/**
 * DialogResult is the Electron save/select return value.
 */
export interface DialogResult {
    canceled: boolean;
    filePath?: string;
}

/**
 * DirectoryConflictChoice is the result of the Drive directory download
 * conflict prompt.
 */
export enum DirectoryConflictChoice {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DirectoryConflictOverwrite = "overwrite",
    DirectoryConflictRename = "rename",
    DirectoryConflictCancel = "cancel",
}

/**
 * DirectoryConflictOptions describes Electron's three-button directory
 * download conflict prompt.
 */
export interface DirectoryConflictOptions {
    Name: string;
}

/**
 * FileFilter matches Electron's dialog.FileFilter.
 */
export interface FileFilter {
    name: string;
    extensions: string[] | null;
}

/**
 * FileWriteAccessResult is the detailed writable check from Electron FS.
 */
export interface FileWriteAccessResult {
    writable: boolean;
    exists: boolean;
    locked: boolean;
    processes: ProcessInfo[] | null;
}

/**
 * ModalOptions is the Electron util:showModal argument.
 */
export interface ModalOptions {
    type: string;
    title: string;
    message: string;
}

/**
 * ModalResult is Electron's MessageBoxReturnValue.
 */
export interface ModalResult {
    response: number;
    checkboxChecked: boolean;
}

/**
 * OpenDialogOptions is the Electron util:showOpenDialog argument.
 */
export interface OpenDialogOptions {
    title: string;
    defaultPath: string;
    filters: FileFilter[] | null;
    properties: string[] | null;
}

/**
 * OpenDialogResult is the Electron showOpenDialog return value.
 */
export interface OpenDialogResult {
    canceled: boolean;
    filePaths: string[] | null;
}

/**
 * PathMetadata is the Electron util:fs:metadata payload.
 */
export interface PathMetadata {
    isDirectory: boolean;
    isFile: boolean;
    size: number;
    mtime: string;
    ctime: string;
    birthtime: string;
}

/**
 * ProcessInfo is the lock-holder shape from Electron native/fs.
 */
export interface ProcessInfo {
    name: string;
    pid: number;
}

/**
 * SaveFileOptions is the Electron saveFileDialog argument.
 */
export interface SaveFileOptions {
    suggestedName: string;
    filters: FileFilter[] | null;
}
