// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CopyStr(str: string): $CancellablePromise<void> {
    return $Call.ByID(4002441979, str);
}

export function GetAppStatus(): $CancellablePromise<$models.AppStatus> {
    return $Call.ByID(548323444);
}

export function GetClipboardFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1193256574);
}

export function OpenCmd(path: string): $CancellablePromise<void> {
    return $Call.ByID(789649135, path);
}

export function OpenExternal(str: string): $CancellablePromise<void> {
    return $Call.ByID(2922584462, str);
}

export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3308331770, path);
}

export function Trash(path: string): $CancellablePromise<void> {
    return $Call.ByID(278060125, path);
}
