export const IPC_EVENT_CHANNELS = [
    "window:blur",
    "window:focus",

    "transfer:update",

    "fn:toast",
    "fn:navi",
    "download:completed",
    "pathSelector:modeSelect",
    "language:update",

    "mod:update-game",
    "mod:update-mods",
    "mod:update-settings",

    "auth:update",
] as const;

export const IPC_HANDLER_CHANNELS = [
    // IPC_HANDLERS_START
    "auth:getSession",
    "auth:isLoggedIn",
    "auth:startLogin",
    "auth:startLogout",
    "drive:delete:items",
    "drive:fn:moveMany",
    "drive:fn:startDownload",
    "drive:fn:startUpload",
    "drive:get:item",
    "drive:patch:rename",
    "drive:post:dir",
    "mod:addGame",
    "mod:applyPreset",
    "mod:copyFolder",
    "mod:createPreset",
    "mod:deletePreset",
    "mod:disableAll",
    "mod:enableAll",
    "mod:exclusiveToggle",
    "mod:extractArchive",
    "mod:getCharacters",
    "mod:getGamePath",
    "mod:getGames",
    "mod:getLastGame",
    "mod:getMods",
    "mod:getPresets",
    "mod:getPreviousFocusedGame",
    "mod:pastePreview",
    "mod:pickFolder",
    "mod:removeGame",
    "mod:selectFolder",
    "mod:setLastGame",
    "mod:toggle",
    "mod:updatePresetName",
    "mod:updateToggleKey",
    "mod:watchCharacter",
    "mod:watchGame",
    "pathSelector:cancel",
    "pathSelector:selectFolderPath",
    "pathSelector:selectModManagerPath",
    "setting:general:checkUpdate",
    "setting:general:getCheckBackgroundUpdates",
    "setting:general:getDefaultStartPage",
    "setting:general:getGameFolderCompressionEnabled",
    "setting:general:getGameFolderCompressionFeatureEnabled",
    "setting:general:getLanguage",
    "setting:general:getMoveTransferPageWhenStartTransfer",
    "setting:general:getPowerSaveBlockInTransfer",
    "setting:general:getRunOnStartup",
    "setting:general:setCheckBackgroundUpdates",
    "setting:general:setDefaultStartPage",
    "setting:general:setGameFolderCompressionEnabled",
    "setting:general:setGameFolderCompressionFeatureEnabled",
    "setting:general:setLanguage",
    "setting:general:setMoveTransferPageWhenStartTransfer",
    "setting:general:setPowerSaveBlockInTransfer",
    "setting:general:setRunOnStartup",
    "setting:mod:getDeleteArchiveAfterExtract",
    "setting:mod:getMoveFolderInsteadOfCopy",
    "setting:mod:getVirtualizationEnabled",
    "setting:mod:getVirtualizationThreshold",
    "setting:mod:setDeleteArchiveAfterExtract",
    "setting:mod:setMoveFolderInsteadOfCopy",
    "setting:mod:setVirtualizationEnabled",
    "setting:mod:setVirtualizationThreshold",
    "setting:net:getProxy",
    "setting:net:setProxy",
    "transfer:cancel",
    "transfer:clear",
    "transfer:list",
    "transfer:pause",
    "transfer:pause-all",
    "transfer:resume",
    "transfer:resume-all",
    "transfer:retry",
    "util:copyStr",
    "util:fs:metadata",
    "util:fs:trash",
    "util:getAppStatus",
    "util:getClipboardFiles",
    "util:openCmd",
    "util:openExternal",
    "util:openPath",
    "util:showModal",
    "util:showOpenDialog",
    "window:openSetting",
    // IPC_HANDLERS_END
] as const;

export type IpcEventChannel = (typeof IPC_EVENT_CHANNELS)[number];
export type IpcHandlerChannel = (typeof IPC_HANDLER_CHANNELS)[number];
