import { Session } from "./schemas/auth";
import { eden } from "@main/client";
import { Treaty } from "@elysiajs/eden";
import { desktop } from "@main/index";
import "./types-check";

export interface AppStatus {
    version: string;
    isPackaged: boolean;
    isDev: boolean;
}

export interface ProxySettings {
    type: "disabled" | "https" | "socks5";
    host?: string;
    port?: string;
    requiresAuth?: boolean;
    username?: string;
    password?: string;
}

interface ToastData {
    description?: string;
}

export interface ToggleKey {
    sectionName: string;
    iniFileName: string;
    key?: string;
    back?: string;
    type?: string;
    variable: string;
    values: string[];
    currentValue?: string;
}

export interface ModInfo {
    name: string;
    path: string;
    isEnabled: boolean;
    preview?: string;
    mtime: number;
    size: number;
    inis: {
        name: string;
        path: string;
        toggleKeys: ToggleKey[];
    }[];
}

export interface FolderGroup {
    name: string;
    path: string;
    mods: ModInfo[];
    preview?: string;
    modCount?: number;
}

export interface Preset {
    id: string;
    game: string;
    name: string;
    mods: string[];
}

export interface PathMetadata {
    isDirectory: boolean;
    isFile: boolean;
    size: number;
    mtime: Date;
    ctime: Date;
    birthtime: Date;
}

export type IpcHandlers = {
    // This section is automatically generated by ipcGeneratorPlugin; do not edit it. 
    // IPC_HANDLERS_START
    "auth:getSession": (...args: Parameters<typeof desktop.service.auth.getSession>) => ReturnType<typeof desktop.service.auth.getSession>;
    "auth:isLoggedIn": (...args: Parameters<typeof desktop.service.auth.isLoggedIn>) => ReturnType<typeof desktop.service.auth.isLoggedIn>;
    "auth:startLogin": (...args: Parameters<typeof desktop.service.auth.startLogin>) => ReturnType<typeof desktop.service.auth.startLogin>;
    "auth:startLogout": (...args: Parameters<typeof desktop.service.auth.startLogout>) => ReturnType<typeof desktop.service.auth.startLogout>;
    "drive:delete:items": (...args: Parameters<typeof desktop.service.drive.delete.items>) => ReturnType<typeof desktop.service.drive.delete.items>;
    "drive:fn:moveMany": (...args: Parameters<typeof desktop.service.drive.fn.moveMany>) => ReturnType<typeof desktop.service.drive.fn.moveMany>;
    "drive:fn:startDownload": (...args: Parameters<typeof desktop.service.drive.fn.startDownload>) => ReturnType<typeof desktop.service.drive.fn.startDownload>;
    "drive:fn:startUpload": (...args: Parameters<typeof desktop.service.drive.fn.startUpload>) => ReturnType<typeof desktop.service.drive.fn.startUpload>;
    "drive:get:item": (...args: Parameters<typeof desktop.service.drive.get.item>) => ReturnType<typeof desktop.service.drive.get.item>;
    "drive:patch:rename": (...args: Parameters<typeof desktop.service.drive.patch.rename>) => ReturnType<typeof desktop.service.drive.patch.rename>;
    "drive:post:dir": (...args: Parameters<typeof desktop.service.drive.post.dir>) => ReturnType<typeof desktop.service.drive.post.dir>;
    "ftm:cancelRun": (...args: Parameters<typeof desktop.service.fixTools.cancelRun>) => ReturnType<typeof desktop.service.fixTools.cancelRun>;
    "ftm:createPreset": (...args: Parameters<typeof desktop.service.fixTools.createPreset>) => ReturnType<typeof desktop.service.fixTools.createPreset>;
    "ftm:deletePreset": (...args: Parameters<typeof desktop.service.fixTools.deletePreset>) => ReturnType<typeof desktop.service.fixTools.deletePreset>;
    "ftm:deleteTool": (...args: Parameters<typeof desktop.service.fixTools.deleteTool>) => ReturnType<typeof desktop.service.fixTools.deleteTool>;
    "ftm:getPresets": (...args: Parameters<typeof desktop.service.fixTools.getPresets>) => ReturnType<typeof desktop.service.fixTools.getPresets>;
    "ftm:getTools": (...args: Parameters<typeof desktop.service.fixTools.getTools>) => ReturnType<typeof desktop.service.fixTools.getTools>;
    "ftm:runFixTool": (...args: Parameters<typeof desktop.service.fixTools.runFixTool>) => ReturnType<typeof desktop.service.fixTools.runFixTool>;
    "ftm:runPreset": (...args: Parameters<typeof desktop.service.fixTools.runPreset>) => ReturnType<typeof desktop.service.fixTools.runPreset>;
    "ftm:saveTool": (...args: Parameters<typeof desktop.service.fixTools.saveTool>) => ReturnType<typeof desktop.service.fixTools.saveTool>;
    "ftm:sendInput": (...args: Parameters<typeof desktop.service.fixTools.sendInput>) => ReturnType<typeof desktop.service.fixTools.sendInput>;
    "mod:addGame": (...args: Parameters<typeof desktop.service.mod.fn.addGame>) => ReturnType<typeof desktop.service.mod.fn.addGame>;
    "mod:applyPreset": (...args: Parameters<typeof desktop.service.mod.fn.applyPreset>) => ReturnType<typeof desktop.service.mod.fn.applyPreset>;
    "mod:copyFolder": (...args: any[]) => any;
    "mod:createPreset": (...args: Parameters<typeof desktop.service.mod.fn.createPreset>) => ReturnType<typeof desktop.service.mod.fn.createPreset>;
    "mod:deletePreset": (...args: Parameters<typeof desktop.service.mod.fn.deletePreset>) => ReturnType<typeof desktop.service.mod.fn.deletePreset>;
    "mod:disableAll": (...args: Parameters<typeof desktop.service.mod.fn.disableAll>) => ReturnType<typeof desktop.service.mod.fn.disableAll>;
    "mod:enableAll": (...args: Parameters<typeof desktop.service.mod.fn.enableAll>) => ReturnType<typeof desktop.service.mod.fn.enableAll>;
    "mod:exclusiveToggle": (...args: Parameters<typeof desktop.service.mod.fn.exclusiveToggle>) => ReturnType<typeof desktop.service.mod.fn.exclusiveToggle>;
    "mod:extractArchive": (...args: Parameters<typeof desktop.service.mod.fn.extractArchiveToGroup>) => ReturnType<typeof desktop.service.mod.fn.extractArchiveToGroup>;
    "mod:getCharacters": (...args: Parameters<typeof desktop.service.mod.get.characters>) => ReturnType<typeof desktop.service.mod.get.characters>;
    "mod:getGamePath": (...args: Parameters<typeof desktop.service.mod.get.gamePath>) => ReturnType<typeof desktop.service.mod.get.gamePath>;
    "mod:getGames": (...args: Parameters<typeof desktop.service.mod.get.games>) => ReturnType<typeof desktop.service.mod.get.games>;
    "mod:getLastGame": (...args: Parameters<typeof desktop.service.mod.get.lastGame>) => ReturnType<typeof desktop.service.mod.get.lastGame>;
    "mod:getMods": (...args: Parameters<typeof desktop.service.mod.get.mods>) => ReturnType<typeof desktop.service.mod.get.mods>;
    "mod:getPresets": (...args: Parameters<typeof desktop.service.mod.get.presets>) => ReturnType<typeof desktop.service.mod.get.presets>;
    "mod:getPreviousFocusedGame": (...args: Parameters<typeof desktop.service.mod.get.previousFocusedGame>) => ReturnType<typeof desktop.service.mod.get.previousFocusedGame>;
    "mod:pastePreview": (...args: Parameters<typeof desktop.service.mod.fn.pastePreview>) => ReturnType<typeof desktop.service.mod.fn.pastePreview>;
    "mod:pickFolder": (...args: any[]) => any;
    "mod:removeGame": (...args: Parameters<typeof desktop.service.mod.fn.removeGame>) => ReturnType<typeof desktop.service.mod.fn.removeGame>;
    "mod:selectFolder": (...args: any[]) => any;
    "mod:setLastGame": (...args: Parameters<typeof desktop.service.mod.fn.setLastGame>) => ReturnType<typeof desktop.service.mod.fn.setLastGame>;
    "mod:toggle": (...args: Parameters<typeof desktop.service.mod.fn.toggle>) => ReturnType<typeof desktop.service.mod.fn.toggle>;
    "mod:updatePresetName": (...args: Parameters<typeof desktop.service.mod.fn.updatePresetName>) => ReturnType<typeof desktop.service.mod.fn.updatePresetName>;
    "mod:updateToggleKey": (...args: any[]) => any;
    "mod:watchCharacter": (...args: Parameters<typeof desktop.service.mod.watchCharacter>) => ReturnType<typeof desktop.service.mod.watchCharacter>;
    "mod:watchGame": (...args: Parameters<typeof desktop.service.mod.watchGame>) => ReturnType<typeof desktop.service.mod.watchGame>;
    "overlay:setIgnoreMouseEvents": (...args: any[]) => any;
    "pathSelector:cancel": (...args: Parameters<typeof desktop.lib.pathSelector.cancelSelection>) => ReturnType<typeof desktop.lib.pathSelector.cancelSelection>;
    "pathSelector:selectFolderPath": (...args: Parameters<typeof desktop.lib.pathSelector.selectFolderPath>) => ReturnType<typeof desktop.lib.pathSelector.selectFolderPath>;
    "pathSelector:selectModManagerPath": (...args: Parameters<typeof desktop.lib.pathSelector.selectModManagerPath>) => ReturnType<typeof desktop.lib.pathSelector.selectModManagerPath>;
    "setting:advanced:getAll": (...args: Parameters<typeof desktop.setting.advanced.getAll>) => ReturnType<typeof desktop.setting.advanced.getAll>;
    "setting:advanced:set": (...args: Parameters<typeof desktop.setting.advanced.set>) => ReturnType<typeof desktop.setting.advanced.set>;
    "setting:general:checkUpdate": (...args: Parameters<typeof desktop.setting.general.checkUpdate>) => ReturnType<typeof desktop.setting.general.checkUpdate>;
    "setting:general:clearImageCache": (...args: Parameters<typeof desktop.setting.general.clearImageCache>) => ReturnType<typeof desktop.setting.general.clearImageCache>;
    "setting:general:getCheckBackgroundUpdates": (...args: Parameters<typeof desktop.setting.general.getCheckBackgroundUpdates>) => ReturnType<typeof desktop.setting.general.getCheckBackgroundUpdates>;
    "setting:general:getDefaultStartPage": (...args: Parameters<typeof desktop.setting.general.getDefaultStartPage>) => ReturnType<typeof desktop.setting.general.getDefaultStartPage>;
    "setting:general:getGameFolderCompressionEnabled": (...args: Parameters<typeof desktop.setting.general.getGameFolderCompressionEnabled>) => ReturnType<typeof desktop.setting.general.getGameFolderCompressionEnabled>;
    "setting:general:getGameFolderCompressionFeatureEnabled": (...args: Parameters<typeof desktop.setting.general.getGameFolderCompressionFeatureEnabled>) => ReturnType<typeof desktop.setting.general.getGameFolderCompressionFeatureEnabled>;
    "setting:general:getImageCacheSize": (...args: Parameters<typeof desktop.setting.general.getImageCacheSize>) => ReturnType<typeof desktop.setting.general.getImageCacheSize>;
    "setting:general:getLanguage": (...args: Parameters<typeof desktop.setting.general.getLanguage>) => ReturnType<typeof desktop.setting.general.getLanguage>;
    "setting:general:getMoveTransferPageWhenStartTransfer": (...args: Parameters<typeof desktop.setting.general.getMoveTransferPageWhenStartTransfer>) => ReturnType<typeof desktop.setting.general.getMoveTransferPageWhenStartTransfer>;
    "setting:general:getPowerSaveBlockInTransfer": (...args: Parameters<typeof desktop.setting.general.getPowerSaveBlockInTransfer>) => ReturnType<typeof desktop.setting.general.getPowerSaveBlockInTransfer>;
    "setting:general:getRunOnStartup": (...args: Parameters<typeof desktop.setting.general.getRunOnStartup>) => ReturnType<typeof desktop.setting.general.getRunOnStartup>;
    "setting:general:setCheckBackgroundUpdates": (...args: Parameters<typeof desktop.setting.general.setCheckBackgroundUpdates>) => ReturnType<typeof desktop.setting.general.setCheckBackgroundUpdates>;
    "setting:general:setDefaultStartPage": (...args: Parameters<typeof desktop.setting.general.setDefaultStartPage>) => ReturnType<typeof desktop.setting.general.setDefaultStartPage>;
    "setting:general:setGameFolderCompressionEnabled": (...args: Parameters<typeof desktop.setting.general.setGameFolderCompressionEnabled>) => ReturnType<typeof desktop.setting.general.setGameFolderCompressionEnabled>;
    "setting:general:setGameFolderCompressionFeatureEnabled": (...args: Parameters<typeof desktop.setting.general.setGameFolderCompressionFeatureEnabled>) => ReturnType<typeof desktop.setting.general.setGameFolderCompressionFeatureEnabled>;
    "setting:general:setLanguage": (...args: Parameters<typeof desktop.setting.general.setLanguage>) => ReturnType<typeof desktop.setting.general.setLanguage>;
    "setting:general:setMoveTransferPageWhenStartTransfer": (...args: Parameters<typeof desktop.setting.general.setMoveTransferPageWhenStartTransfer>) => ReturnType<typeof desktop.setting.general.setMoveTransferPageWhenStartTransfer>;
    "setting:general:setPowerSaveBlockInTransfer": (...args: Parameters<typeof desktop.setting.general.setPowerSaveBlockInTransfer>) => ReturnType<typeof desktop.setting.general.setPowerSaveBlockInTransfer>;
    "setting:general:setRunOnStartup": (...args: Parameters<typeof desktop.setting.general.setRunOnStartup>) => ReturnType<typeof desktop.setting.general.setRunOnStartup>;
    "setting:mod:getDeleteArchiveAfterExtract": (...args: Parameters<typeof desktop.setting.mod.getDeleteArchiveAfterExtract>) => ReturnType<typeof desktop.setting.mod.getDeleteArchiveAfterExtract>;
    "setting:mod:getMoveFolderInsteadOfCopy": (...args: Parameters<typeof desktop.setting.mod.getMoveFolderInsteadOfCopy>) => ReturnType<typeof desktop.setting.mod.getMoveFolderInsteadOfCopy>;
    "setting:mod:getSearchModPreview": (...args: Parameters<typeof desktop.setting.mod.getSearchModPreview>) => ReturnType<typeof desktop.setting.mod.getSearchModPreview>;
    "setting:mod:getVirtualizationEnabled": (...args: Parameters<typeof desktop.setting.mod.getVirtualizationEnabled>) => ReturnType<typeof desktop.setting.mod.getVirtualizationEnabled>;
    "setting:mod:getVirtualizationThreshold": (...args: Parameters<typeof desktop.setting.mod.getVirtualizationThreshold>) => ReturnType<typeof desktop.setting.mod.getVirtualizationThreshold>;
    "setting:mod:setDeleteArchiveAfterExtract": (...args: any[]) => any;
    "setting:mod:setMoveFolderInsteadOfCopy": (...args: any[]) => any;
    "setting:mod:setSearchModPreview": (...args: any[]) => any;
    "setting:mod:setVirtualizationEnabled": (...args: any[]) => any;
    "setting:mod:setVirtualizationThreshold": (...args: any[]) => any;
    "setting:net:getProxy": (...args: Parameters<typeof desktop.setting.net.getProxy>) => ReturnType<typeof desktop.setting.net.getProxy>;
    "setting:net:setProxy": (...args: Parameters<typeof desktop.setting.net.setProxy>) => ReturnType<typeof desktop.setting.net.setProxy>;
    "setting:overlay:getEnabled": (...args: Parameters<typeof desktop.setting.overlay.getEnabled>) => ReturnType<typeof desktop.setting.overlay.getEnabled>;
    "setting:overlay:getToggleKey": (...args: Parameters<typeof desktop.setting.overlay.getToggleKey>) => ReturnType<typeof desktop.setting.overlay.getToggleKey>;
    "setting:overlay:setEnabled": (...args: any[]) => any;
    "setting:overlay:setToggleKey": (...args: any[]) => any;
    "tools:buildNewD3DDLL": (...args: Parameters<typeof desktop.service.tools.buildNewD3DDLL>) => ReturnType<typeof desktop.service.tools.buildNewD3DDLL>;
    "tools:getGIMIPath": (...args: Parameters<typeof desktop.service.tools.getGIMIPath>) => ReturnType<typeof desktop.service.tools.getGIMIPath>;
    "tools:saveGIMIPath": (...args: Parameters<typeof desktop.service.tools.saveGIMIPath>) => ReturnType<typeof desktop.service.tools.saveGIMIPath>;
    "transfer:cancel": (...args: Parameters<typeof desktop.service.transfer.cancelTransfer>) => ReturnType<typeof desktop.service.transfer.cancelTransfer>;
    "transfer:clear": (...args: any[]) => any;
    "transfer:list": (...args: Parameters<typeof desktop.service.transfer.getAllTransfer>) => ReturnType<typeof desktop.service.transfer.getAllTransfer>;
    "transfer:pause": (...args: any[]) => any;
    "transfer:pause-all": (...args: any[]) => any;
    "transfer:resume": (...args: any[]) => any;
    "transfer:resume-all": (...args: any[]) => any;
    "transfer:retry": (...args: any[]) => any;
    "util:copyStr": (...args: Parameters<typeof import("@main/services/util").copyStr>) => ReturnType<typeof import("@main/services/util").copyStr>;
    "util:fs:metadata": (...args: Parameters<typeof import("@main/services/util").getPathMetadata>) => ReturnType<typeof import("@main/services/util").getPathMetadata>;
    "util:fs:trash": (...args: Parameters<typeof import("@main/services/util").trash>) => ReturnType<typeof import("@main/services/util").trash>;
    "util:getAppStatus": (...args: Parameters<typeof import("@main/services/util").getAppStatus>) => ReturnType<typeof import("@main/services/util").getAppStatus>;
    "util:getClipboardFiles": (...args: Parameters<typeof import("@main/services/util").getClipboardFiles>) => ReturnType<typeof import("@main/services/util").getClipboardFiles>;
    "util:openCmd": (...args: Parameters<typeof import("@main/services/util").openCmd>) => ReturnType<typeof import("@main/services/util").openCmd>;
    "util:openExternal": (...args: Parameters<typeof import("@main/services/util").openExternal>) => ReturnType<typeof import("@main/services/util").openExternal>;
    "util:openPath": (...args: Parameters<typeof import("@main/services/util").openPath>) => ReturnType<typeof import("@main/services/util").openPath>;
    "util:showModal": (...args: Parameters<typeof import("@main/services/util").showModal>) => ReturnType<typeof import("@main/services/util").showModal>;
    "util:showOpenDialog": (...args: Parameters<typeof import("@main/services/util").showOpenDialog>) => ReturnType<typeof import("@main/services/util").showOpenDialog>;
    "window:openSetting": (...args: any[]) => any;
    "xxmi:findXXMIPath": (...args: Parameters<typeof desktop.service.xxmi.findXXMIPath>) => ReturnType<typeof desktop.service.xxmi.findXXMIPath>;
    "xxmi:getEnabledImporters": (...args: Parameters<typeof desktop.service.xxmi.getEnabledImporters>) => ReturnType<typeof desktop.service.xxmi.getEnabledImporters>;
    "xxmi:getXXMIConfig": (...args: Parameters<typeof desktop.service.xxmi.getXXMIConfig>) => ReturnType<typeof desktop.service.xxmi.getXXMIConfig>;
    "xxmi:getXXMIData": (...args: Parameters<typeof desktop.service.xxmi.getXXMIData>) => ReturnType<typeof desktop.service.xxmi.getXXMIData>;
    "xxmi:getXXMIPath": (...args: Parameters<typeof desktop.service.xxmi.getXXMIPath>) => ReturnType<typeof desktop.service.xxmi.getXXMIPath>;
    "xxmi:saveXXMIPath": (...args: Parameters<typeof desktop.service.xxmi.saveXXMIPath>) => ReturnType<typeof desktop.service.xxmi.saveXXMIPath>;
    "xxmi:startGame": (...args: Parameters<typeof desktop.service.xxmi.startGame>) => ReturnType<typeof desktop.service.xxmi.startGame>;
    // IPC_HANDLERS_END
};

export interface GameConfig {
    game: string;
    modFolderPath: string;
}

export type IpcEvents = {
    "window:blur": () => void;
    "window:focus": () => void;

    "transfer:update": (transfers: Transfer[]) => void;

    "fn:toast": (message: string, data?: ToastData) => void;
    "fn:navi": (path: string) => void;
    "download:completed": (data: { path: string; name: string; disableToast?: boolean }) => void;
    "pathSelector:modeSelect": (data: { selectionId: string; suggestedName?: string }) => void;
    "language:update": (language: string) => void;

    "mod:update-game": () => void;
    "mod:update-mods": () => void;
    "mod:update-settings": () => void;

    "auth:update": (session: Session | null) => void;
    "setting:update": (data: { key: string; value: any }) => void;
    "compact:log": (message: string) => void;
    "compact:progress": (payload: {
        message: string;
        processedFiles: number;
        skippedFiles: number;
        errorFiles: number;
    }) => void;
    "tools:progress": (message: string) => void;
    "ftm:log": (message: string) => void;

    "renderer:reload": () => void;
};


const akashaModIdGet = eden.akasha.content({ id: "" }).get;
export type ModIdGetResp = Treaty.Data<typeof akashaModIdGet>;
export type Content = {
    id: string;
    name: string;
    isDir: boolean;
    size: number | null;
    mimeType: string | null;
    parentId: string | null;
    createdAt: Date;
    updatedAt: Date;
    preview?: {
        img?: {
            default: string;
            cover: string | null;
            thumbnail: string | null;
        };
        video?: {
            default: string;
            // stream: string;
        };
    } | null;
    link?: {
        id: string;
        password: boolean;
        expiresAt: Date | null;
        url: string;
    } | null;
};

export type TransferStatus =
    | "pending"
    | "preparing"
    | "progress"
    | "completed"
    | "paused"
    | "canceled"
    | "error";

export interface TransferData {
    root?: {
        id: string;
        parentId: string | null;
        name: string;
    };
    files: {
        id: string;
        fileId: string;
        parentId: string | null;
        name: string;
        size: number;
        compAlg: "gzip" | "zstd" | null;
        url: string;
    }[];
    dirs: {
        id: string;
        parentId: string | null;
        name: string;
    }[];
}

export interface Transfer {
    pid: string;
    type: "upload" | "download";
    status: TransferStatus;
    totalSize: number;
    transferedSize: number;
    progress: number;
    speed: number; // bytes per second
    eta: number; // seconds
    startTime: number;
    data: TransferData;
    name: string;
    totalFiles: number;
    transferedFiles: number;
    failedFiles: number;
    path?: string;
}
export type TransferWithoutData = Omit<Transfer, "data">;
