import path from "node:path";

import fse from "fs-extra";

import {
    appendResourceSuffix,
    classifyLine,
    isControlFlowLine,
    isResourceReference,
} from "./ini-text";
import { disableIniFile, recordFileWrite, type RollbackAction } from "./rollback";

type ClassicSource = {
    iniPath: string;
    groupIndex: number;
};

type SectionEntry = {
    key: string;
    value: string;
};

type SectionData = {
    header: string;
    name: string;
    entries: SectionEntry[];
    location: string;
    groupIndex: number;
};

const RECOGNIZED = [
    "TextureOverride",
    "ShaderOverride",
    "Resource",
    "Constants",
    "Present",
    "CommandList",
    "CustomShader",
] as const;

export async function writeClassicMerge(options: {
    outputDir: string;
    sources: ClassicSource[];
    forwardKey: string;
    backKey?: string;
    created?: RollbackAction[];
}) {
    const sections = (
        await Promise.all(
            options.sources.map(async (source) => {
                const text = await fse.readFile(source.iniPath, "utf8");
                return parseClassicSections(text, path.dirname(source.iniPath), source.groupIndex);
            }),
        )
    ).flat();

    const commandData = new Map<string, SectionData[]>();
    const overrides: string[] = [];
    const resources: string[] = [];

    for (const section of sections) {
        const hash = getEntryValue(section, "hash");
        if (hash) {
            const index = getEntryValue(section, "match_first_index") ?? "-1";
            const key = `${hash.toLowerCase()}::${index}`;
            const existing = commandData.get(key);
            if (!existing) {
                commandData.set(key, [section]);
                overrides.push(buildOverride(section, options.forwardKey !== ""));
            } else {
                existing.push(section);
            }
            continue;
        }

        if (section.header === "CommandList") {
            const key = `${section.name}::0`;
            const existing = commandData.get(key) ?? [];
            existing.push(section);
            commandData.set(key, existing);
            continue;
        }

        if (hasEntry(section, "filename") || hasEntry(section, "type")) {
            resources.push(buildResource(section, options.outputDir));
        }
    }

    const swapValues = options.sources.map((source) => String(source.groupIndex)).join(",");
    const constants = [
        "[Constants]",
        "global persist $swapvar = 0",
        "global $active",
        "global $creditinfo = 0",
        "",
        "[KeySwap]",
        "condition = $active == 1",
        `key = ${options.forwardKey}`,
        ...(options.backKey ? [`back = ${options.backKey}`] : []),
        "type = cycle",
        `$swapvar = ${swapValues}`,
        "$creditinfo = 0",
        "",
        "[Present]",
        "post $active = 0",
        "",
    ].join("\n");

    const commands = [...commandData.values()]
        .filter((group) => !group[0].name.includes("VertexLimitRaise"))
        .map((group) => buildCommandList(group))
        .join("\n");

    const headerLines = options.sources.map((source) => {
        const rel = path.relative(options.outputDir, source.iniPath);
        const formatted = path.isAbsolute(rel) || rel.startsWith(".") ? rel : `.\\${rel}`;
        return `; Merged Mod: ${formatted}`;
    });
    const result = [
        ...headerLines,
        "",
        constants,
        "; Overrides ---------------------------",
        "",
        overrides.join("\n"),
        "; CommandList -------------------------",
        "",
        commands,
        "; Resources ---------------------------",
        "",
        resources.join("\n"),
        "",
        "; .ini generated by Nahida Desktop mod merger",
        "",
    ].join("\n");

    const created = options.created ?? [];
    const outputPath = path.join(options.outputDir, "merged.ini");
    await recordFileWrite(outputPath, created);
    await fse.writeFile(outputPath, result, "utf8");

    await Promise.all(
        options.sources.map(async (source) => {
            if (await fse.pathExists(source.iniPath)) {
                await disableIniFile(source.iniPath, created);
            }
        }),
    );

    return outputPath;
}

function parseClassicSections(text: string, location: string, groupIndex: number) {
    const sections: SectionData[] = [];
    let current: SectionData | null = null;

    for (const raw of text.split(/\r?\n/)) {
        const line = classifyLine(raw);
        if (line.kind === "header") {
            const recognized = RECOGNIZED.find((header) => line.name.startsWith(header));
            if (!recognized) {
                current = null;
                continue;
            }
            if (
                line.name.includes("CommandListReflectionTexture") ||
                line.name.includes("CommandListOutline")
            ) {
                current = null;
                continue;
            }
            current = {
                header: recognized,
                name: line.name.slice(recognized.length),
                entries: [],
                location,
                groupIndex,
            };
            sections.push(current);
            continue;
        }
        if (!current || line.kind !== "kv" || isControlFlowLine(line.raw)) continue;
        if (line.key.includes("CharacterIB") || line.key.includes("ResourceRef")) continue;
        current.entries.push({ key: line.key, value: line.value });
    }

    return sections;
}

function getEntryValue(section: SectionData, keyName: string) {
    const target = keyName.toLowerCase();
    const entry = section.entries.find((item) => item.key.toLowerCase() === target);
    return entry?.value ?? null;
}

function hasEntry(section: SectionData, keyName: string) {
    const target = keyName.toLowerCase();
    return section.entries.some((item) => item.key.toLowerCase() === target);
}

function buildOverride(section: SectionData, setActive: boolean) {
    const hash = getEntryValue(section, "hash");
    const lines = [`[${section.header}${section.name}]`, `hash = ${hash}`];
    const matchFirstIndex = getEntryValue(section, "match_first_index");
    if (matchFirstIndex) {
        lines.push(`match_first_index = ${matchFirstIndex}`);
    }

    const preserveKeys = [
        "allow_duplicate_hash",
        "filter_index",
        "match_priority",
        "cull",
        "topology",
        "override_vertex_count",
        "override_byte_stride",
    ];

    for (const entry of section.entries) {
        const lower = entry.key.toLowerCase();
        if (preserveKeys.includes(lower)) {
            lines.push(`${entry.key} = ${entry.value}`);
        }
    }

    if (!section.name.includes("VertexLimitRaise")) {
        lines.push(`run = CommandList${section.name}`);
    }
    if (setActive && section.name.includes("Position")) {
        lines.push("$active = 1");
    }
    lines.push("");
    return lines.join("\n");
}

function buildResource(section: SectionData, outputDir: string) {
    const lines = [`[${section.header}${section.name}.${section.groupIndex}]`];
    for (const entry of section.entries) {
        if (entry.key.toLowerCase() === "filename") {
            const rawPath = entry.value.replace(/^["']|["']$/g, "").trim();
            const absTarget = path.isAbsolute(rawPath)
                ? rawPath
                : path.resolve(section.location, rawPath);
            const relTarget = path.relative(outputDir, absTarget);
            const formatted = relTarget.startsWith(".") ? relTarget : `.\\${relTarget}`;
            lines.push(`${entry.key} = ${formatted}`);
            continue;
        }
        lines.push(`${entry.key} = ${entry.value}`);
    }
    lines.push("");
    return lines.join("\n");
}

function buildCommandList(group: SectionData[]) {
    const lines = [`[CommandList${group[0].name}]`];
    const excludedKeys = [
        "hash",
        "match_first_index",
        "allow_duplicate_hash",
        "override_vertex_count",
        "override_byte_stride",
    ];

    group.forEach((model, index) => {
        lines.push(`${index === 0 ? "if" : "else if"} $swapvar == ${model.groupIndex}`);
        for (const entry of model.entries) {
            const lowerKey = entry.key.toLowerCase();
            if (excludedKeys.includes(lowerKey)) continue;

            if (isResourceReference(entry.key, entry.value)) {
                const suffixed = appendResourceSuffix(entry.value, model.groupIndex);
                lines.push(`\t${entry.key} = ${suffixed}`);
            } else {
                lines.push(`\t${entry.key} = ${entry.value}`);
            }
        }
    });
    lines.push("endif", "");
    return lines.join("\n");
}
