import path from "node:path";

import fse from "fs-extra";

import { classifyLine } from "./ini-text";

type ClassicSource = {
    iniPath: string;
    groupIndex: number;
};

type SectionData = {
    header: string;
    name: string;
    values: Record<string, string>;
    location: string;
    groupIndex: number;
};

const RECOGNIZED = [
    "TextureOverride",
    "ShaderOverride",
    "Resource",
    "Constants",
    "Present",
    "CommandList",
    "CustomShader",
] as const;

export async function writeClassicMerge(options: {
    outputDir: string;
    sources: ClassicSource[];
    forwardKey: string;
    backKey?: string;
}) {
    const sections = (
        await Promise.all(
            options.sources.map(async (source) => {
                const text = await fse.readFile(source.iniPath, "utf8");
                return parseClassicSections(text, path.dirname(source.iniPath), source.groupIndex);
            }),
        )
    ).flat();

    const commandData = new Map<string, SectionData[]>();
    const overrides: string[] = [];
    const resources: string[] = [];

    for (const section of sections) {
        if (section.values.hash) {
            const index = section.values.match_first_index ?? "-1";
            const key = `${section.values.hash.toLowerCase()}::${index}`;
            const existing = commandData.get(key);
            if (!existing) {
                commandData.set(key, [section]);
                overrides.push(buildOverride(section, options.forwardKey !== ""));
            } else {
                existing.push(section);
            }
            continue;
        }

        if (section.header === "CommandList") {
            const key = `${section.name}::0`;
            const existing = commandData.get(key) ?? [];
            existing.push(section);
            commandData.set(key, existing);
            continue;
        }

        if (section.values.filename || section.values.type) {
            resources.push(buildResource(section));
        }
    }

    const swapValues = options.sources.map((source) => String(source.groupIndex)).join(",");
    const constants = [
        "[Constants]",
        "global persist $swapvar = 0",
        "global $active",
        "global $creditinfo = 0",
        "",
        "[KeySwap]",
        "condition = $active == 1",
        `key = ${options.forwardKey}`,
        ...(options.backKey ? [`back = ${options.backKey}`] : []),
        "type = cycle",
        `$swapvar = ${swapValues}`,
        "$creditinfo = 0",
        "",
        "[Present]",
        "post $active = 0",
        "",
    ].join("\n");

    const commands = [...commandData.values()]
        .filter((group) => !group[0].name.includes("VertexLimitRaise"))
        .map((group) => buildCommandList(group))
        .join("\n");

    const headerPaths = options.sources.map((source) => source.iniPath).join(", ");
    const result = [
        `; Merged Mod: ${headerPaths}`,
        "",
        constants,
        "; Overrides ---------------------------",
        "",
        overrides.join("\n"),
        "; CommandList -------------------------",
        "",
        commands,
        "; Resources ---------------------------",
        "",
        resources.join("\n"),
        "",
        "; .ini generated by Nahida Desktop mod merger",
        "",
    ].join("\n");

    const outputPath = path.join(options.outputDir, "merged.ini");
    await fse.writeFile(outputPath, result, "utf8");

    await Promise.all(
        options.sources.map(async (source) => {
            const disabledPath = path.join(
                path.dirname(source.iniPath),
                `DISABLED${path.basename(source.iniPath)}`,
            );
            if (await fse.pathExists(source.iniPath)) {
                await fse.move(source.iniPath, disabledPath, { overwrite: true });
            }
        }),
    );

    return outputPath;
}

function parseClassicSections(text: string, location: string, groupIndex: number) {
    const sections: SectionData[] = [];
    let current: SectionData | null = null;

    for (const raw of text.split(/\r?\n/)) {
        const line = classifyLine(raw);
        if (line.kind === "header") {
            const recognized = RECOGNIZED.find((header) => line.name.startsWith(header));
            if (!recognized) {
                current = null;
                continue;
            }
            if (
                line.name.includes("CommandListReflectionTexture") ||
                line.name.includes("CommandListOutline")
            ) {
                current = null;
                continue;
            }
            current = {
                header: recognized,
                name: line.name.slice(recognized.length),
                values: {},
                location,
                groupIndex,
            };
            sections.push(current);
            continue;
        }
        if (!current || line.kind !== "kv") continue;
        if (line.key.includes("CharacterIB") || line.key.includes("ResourceRef")) continue;
        current.values[line.key] = line.value;
    }

    return sections;
}

function buildOverride(section: SectionData, setActive: boolean) {
    const lines = [`[${section.header}${section.name}]`, `hash = ${section.values.hash}`];
    if (section.values.match_first_index) {
        lines.push(`match_first_index = ${section.values.match_first_index}`);
    }
    if (!section.name.includes("VertexLimitRaise")) {
        lines.push(`run = CommandList${section.name}`);
    }
    if (setActive && section.name.includes("Position")) {
        lines.push("$active = 1");
    }
    lines.push("");
    return lines.join("\n");
}

function buildResource(section: SectionData) {
    const lines = [`[${section.header}${section.name}.${section.groupIndex}]`];
    for (const [key, value] of Object.entries(section.values)) {
        if (key === "filename") {
            lines.push(`${key} = ${path.join(section.location, value)}`);
            continue;
        }
        lines.push(`${key} = ${value}`);
    }
    lines.push("");
    return lines.join("\n");
}

function buildCommandList(group: SectionData[]) {
    const lines = [`[CommandList${group[0].name}]`];
    group.forEach((model, index) => {
        lines.push(`${index === 0 ? "if" : "else if"} $swapvar == ${model.groupIndex}`);
        for (const [key, value] of Object.entries(model.values)) {
            if (["hash", "match_first_index"].includes(key.toLowerCase())) continue;
            const suffix =
                (key.startsWith("vb") ||
                    key.startsWith("ib") ||
                    key.startsWith("ps") ||
                    key.startsWith("vs") ||
                    key.startsWith("th") ||
                    value.includes("Resource")) &&
                value.toLowerCase() !== "null"
                    ? `.${model.groupIndex}`
                    : "";
            lines.push(`\t${key} = ${value}${suffix}`);
        }
    });
    lines.push("endif", "");
    return lines.join("\n");
}
