import path from "node:path";

import fg from "fast-glob";
import fse from "fs-extra";

import {
    classifyLine,
    extractMergedModPaths,
    extractNamespace,
    extractPositionHash,
    hasMasterSwapRef,
    parseIniText,
    serializeIni,
} from "./ini-text";
import { ensureMergeBackup, recordFileWrite, type RollbackAction } from "./rollback";

export async function writeNamespaceMerge(options: {
    masterDir: string;
    name: string;
    sources: { iniPath: string; index: number }[];
    forwardKey: string;
    backKey: string;
    includeVanilla: boolean;
    existingMasterPath?: string;
    created?: RollbackAction[];
}) {
    const created = options.created ?? [];
    const wrapSources = await Promise.all(
        options.sources.map(async (source) => {
            await ensureMergeBackup(source.iniPath, created);
            const text = await unwrapNamespace(await fse.readFile(source.iniPath, "utf8"));
            await recordFileWrite(source.iniPath, created);
            await fse.writeFile(
                source.iniPath,
                wrapHashedSections(text, options.name, source.index),
                "utf8",
            );
            return source.iniPath;
        }),
    );

    const firstHashSource = wrapSources[0];
    const positionHash = firstHashSource
        ? extractPositionHash(await fse.readFile(firstHashSource, "utf8"))
        : null;
    const swapCount = Math.max(...options.sources.map((source) => source.index), 0) + 1;
    const swapValues = Array.from({ length: swapCount }, (_, index) => String(index)).join(",");
    const listed = [
        ...(options.existingMasterPath
            ? extractMergedModPaths(await fse.readFile(options.existingMasterPath, "utf8"))
            : []),
        ...wrapSources,
    ];

    const uniqueListed = [...new Set(listed)];
    const master = [
        ...uniqueListed.map((entry) => `; Merged Mod: ${entry}`),
        `namespace = ${options.name}\\Master`,
        "",
        "; Constants ---------------------------",
        "",
        "[Constants]",
        "global persist $swapvar = 0",
        "global $active",
        "global $creditinfo = 0",
        "",
        "[KeySwap]",
        "condition = $active == 1",
        `key = ${options.forwardKey}`,
        `back = ${options.backKey}`,
        "type = cycle",
        `$swapvar = ${swapValues}`,
        "$creditinfo = 0",
        "",
        "[Present]",
        "post $active = 0",
        "",
        `[TextureOverride${options.name}Position]`,
        ...(positionHash ? [`hash = ${positionHash}`] : [";None found"]),
        "$active = 1",
        "",
        "; .ini generated by Nahida Desktop namespace merger",
        "",
    ].join("\n");

    const masterPath = path.join(options.masterDir, `Master${options.name}.ini`);
    await recordFileWrite(masterPath, created);
    await fse.writeFile(masterPath, master, "utf8");
    return masterPath;
}

export async function collectNamespaceChildren(masterPath: string) {
    const masterDir = path.dirname(masterPath);
    const text = await fse.readFile(masterPath, "utf8");
    const namespace = extractNamespace(text);
    const listed = extractMergedModPaths(text).map((entry) => path.resolve(masterDir, entry));
    if (listed.length > 0) {
        return listed.filter((entry) => fse.pathExistsSync(entry));
    }

    const token = namespace?.replace(/\\Master$/i, "") ?? "";
    const pattern = token
        ? new RegExp(`\\$\\\\${escapeRegExp(token)}\\\\Master\\\\swapvar`, "i")
        : /\$\\[^\\\s]+\\Master\\swapvar/i;
    const walk = await fg("**/*.ini", {
        cwd: masterDir,
        absolute: true,
        onlyFiles: true,
        caseSensitiveMatch: false,
    });
    return walk.filter((candidate) => {
        if (path.resolve(candidate) === path.resolve(masterPath)) return false;
        if (!fse.pathExistsSync(candidate)) return false;
        const child = fse.readFileSync(candidate, "utf8");
        return pattern.test(child) || hasMasterSwapRef(child);
    });
}

export async function unwrapNamespace(text: string) {
    const parsed = parseIniText(text);
    parsed.sections = parsed.sections.map((section) => ({
        ...section,
        lines: unwrapSectionLines(section.lines),
    }));
    return serializeIni(parsed);
}

function unwrapSectionLines(lines: ReturnType<typeof parseIniText>["sections"][number]["lines"]) {
    const nextLines: typeof lines = [];
    let depth = 0;
    for (const [index, line] of lines.entries()) {
        const trimmed = line.raw.trim().toLowerCase();
        if (depth === 0 && line.kind === "kv" && line.key.toLowerCase() === "match_priority") {
            const upcoming = lines.slice(index + 1).find((entry) => entry.raw.trim() !== "");
            if (upcoming && /if\s+\$\\[^\\\s]+\\master\\swapvar/i.test(upcoming.raw)) continue;
        }
        if (trimmed.startsWith("if ") && /\$\\[^\\\s]+\\master\\swapvar/i.test(line.raw)) {
            depth += 1;
            continue;
        }
        if (
            depth === 1 &&
            trimmed.startsWith("else if ") &&
            /\$\\[^\\\s]+\\master\\swapvar/i.test(line.raw)
        ) {
            continue;
        }
        if (depth > 0 && (trimmed.startsWith("if ") || trimmed.startsWith("else if "))) {
            depth += 1;
        }
        if (depth > 0 && trimmed === "endif") {
            depth -= 1;
            continue;
        }
        nextLines.push(
            depth > 0 && (line.kind === "kv" || line.kind === "other" || line.kind === "comment")
                ? classifyLine(line.raw.replace(/^\t/, ""))
                : line,
        );
    }
    return nextLines;
}

export function wrapHashedSections(text: string, name: string, index: number) {
    const lines = text.split(/\r?\n/);
    const output: string[] = [];
    let wrapping = false;
    let pending: string[] = [];

    const flush = () => {
        if (!wrapping) return;
        const block = pending;
        pending = [];
        wrapping = false;
        output.push(...closeWrap(block));
    };

    for (const raw of lines) {
        const trimmed = raw.trim().toLowerCase();
        if (
            wrapping &&
            (trimmed.startsWith("[") || trimmed.startsWith("hash =") || trimmed.startsWith("hash="))
        ) {
            flush();
        }
        if (!wrapping && (trimmed.startsWith("hash =") || trimmed.startsWith("hash="))) {
            output.push(raw);
            output.push(`match_priority = ${index}`);
            output.push(`if $\\${name}\\Master\\swapvar==${index}`);
            wrapping = true;
            continue;
        }
        if (wrapping) {
            pending.push(raw);
            continue;
        }
        output.push(raw);
    }
    flush();
    return `${output.join("\n").replace(/\n+$/, "")}\n`;
}

function closeWrap(block: string[]) {
    let lastCode = -1;
    const next = block.map((line, index) => {
        const trimmed = line.trim();
        if (trimmed.startsWith(";")) return trimmed;
        if (trimmed !== "" && !trimmed.startsWith("[")) lastCode = index;
        return trimmed === "" || trimmed.startsWith("[") ? line : `\t${line.replace(/^\t/, "")}`;
    });
    if (lastCode >= 0) {
        next.splice(lastCode + 1, 0, "endif", "");
        return next;
    }
    next.push("endif", "");
    return next;
}

function escapeRegExp(value: string) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
