import path from "node:path";

import fg from "fast-glob";
import fse from "fs-extra";

import {
    classifyLine,
    detectDialect,
    extractMergedModPaths,
    extractNamespace,
    extractPositionHash,
    extractPositionSectionHash,
    hasMasterSwapRef,
    isBackupIniName,
    isFileDisabledIniName,
    isHelperIniName,
    parseIniText,
    serializeIni,
} from "./ini-text";
import { ensureMergeBackup, recordFileWrite, type RollbackAction } from "./rollback";

export async function writeNamespaceMerge(options: {
    masterDir: string;
    name: string;
    sources: { iniPath: string; index: number }[];
    forwardKey: string;
    backKey: string;
    includeVanilla: boolean;
    existingMasterPath?: string;
    created?: RollbackAction[];
}) {
    const created = options.created ?? [];
    const wrapSources = await Promise.all(
        options.sources.map(async (source) => {
            await ensureMergeBackup(source.iniPath, created);
            const text = await unwrapNamespace(await fse.readFile(source.iniPath, "utf8"));
            const wrapped = wrapHashedSections(text, options.name, source.index);
            await recordFileWrite(source.iniPath, created);
            await fse.writeFile(source.iniPath, wrapped, "utf8");
            return { iniPath: source.iniPath, text: wrapped };
        }),
    );

    const representative =
        wrapSources.find(
            (entry) =>
                !isHelperIniName(path.basename(entry.iniPath)) &&
                extractPositionSectionHash(entry.text) !== null,
        ) ??
        wrapSources.find(
            (entry) =>
                !isHelperIniName(path.basename(entry.iniPath)) &&
                extractPositionHash(entry.text) !== null,
        ) ??
        wrapSources.find((entry) => !isHelperIniName(path.basename(entry.iniPath))) ??
        wrapSources.find((entry) => extractPositionSectionHash(entry.text) !== null) ??
        wrapSources[0];

    const representativeText = representative?.text ?? "";
    const positionHash = representative ? extractPositionHash(representativeText) : null;
    const dialect = representativeText ? detectDialect(representativeText) : "unknown";

    const representativeSectionName =
        dialect === "wwmi"
            ? `TextureOverride${options.name}MarkBoneDataCB`
            : dialect === "efmi"
              ? `TextureOverride${options.name}Component0`
              : `TextureOverride${options.name}Position`;

    const extractedSwapIndices = wrapSources.flatMap((entry) =>
        [...entry.text.matchAll(/\$\\[^\\\s]+\\Master\\swapvar\w*==(\d+)/gi)].map((m) =>
            Number(m[1]),
        ),
    );
    const maxSwapIndex = Math.max(
        ...options.sources.map((source) => source.index),
        ...extractedSwapIndices,
        0,
    );
    const swapCount = maxSwapIndex + 1;
    const swapValues = Array.from({ length: swapCount }, (_, index) => String(index)).join(",");
    const existingDir = options.existingMasterPath
        ? path.dirname(options.existingMasterPath)
        : options.masterDir;
    const existingListed = options.existingMasterPath
        ? extractMergedModPaths(await fse.readFile(options.existingMasterPath, "utf8")).map(
              (entry) => path.resolve(existingDir, entry),
          )
        : [];
    const currentSources = wrapSources.map((entry) =>
        path.resolve(options.masterDir, entry.iniPath),
    );
    const uniqueListed = [...new Set([...existingListed, ...currentSources])];
    const master = [
        ...uniqueListed.map((entry) => {
            const rel = path.relative(options.masterDir, entry);
            const formatted = path.isAbsolute(rel) || rel.startsWith(".") ? rel : `.\\${rel}`;
            return `; Merged Mod: ${formatted}`;
        }),
        `namespace = ${options.name}\\Master`,
        "",
        "; Constants ---------------------------",
        "",
        "[Constants]",
        "global persist $swapvar = 0",
        "global $active",
        "global $creditinfo = 0",
        "",
        "[KeySwap]",
        "condition = $active == 1",
        `key = ${options.forwardKey}`,
        `back = ${options.backKey}`,
        "type = cycle",
        `$swapvar = ${swapValues}`,
        "$creditinfo = 0",
        "",
        "[Present]",
        "post $active = 0",
        "",
        ...(positionHash
            ? [`[${representativeSectionName}]`, `hash = ${positionHash}`, "$active = 1", ""]
            : []),
        "; .ini generated by Nahida Desktop namespace merger",
        "",
    ].join("\n");

    const masterPath = path.join(options.masterDir, `Master${options.name}.ini`);
    await recordFileWrite(masterPath, created);
    await fse.writeFile(masterPath, master, "utf8");
    return masterPath;
}

export async function collectNamespaceChildren(masterPath: string) {
    const masterDir = path.dirname(masterPath);
    const text = await fse.readFile(masterPath, "utf8");
    const namespace = extractNamespace(text);
    const listed = (
        await Promise.all(
            extractMergedModPaths(text)
                .map((entry) => path.resolve(masterDir, entry))
                .map(async (entry) => {
                    const content = await fse.readFile(entry, "utf8").catch(() => null);
                    return content !== null ? entry : null;
                }),
        )
    ).filter((entry): entry is string => entry !== null);

    const token = namespace?.replace(/\\Master$/i, "") ?? "";
    const pattern = token
        ? new RegExp(`\\$\\\\${escapeRegExp(token)}\\\\Master\\\\swapvar`, "i")
        : /\$\\[^\\\s]+\\Master\\swapvar/i;
    const walk = await fg("**/*.ini", {
        cwd: masterDir,
        absolute: true,
        onlyFiles: true,
        caseSensitiveMatch: false,
    });
    const scanned = (
        await Promise.all(
            walk
                .filter((candidate) => {
                    if (path.resolve(candidate) === path.resolve(masterPath)) return false;
                    const fileName = path.basename(candidate);
                    return !isFileDisabledIniName(fileName) && !isBackupIniName(fileName);
                })
                .map(async (candidate) => {
                    const child = await fse.readFile(candidate, "utf8").catch(() => null);
                    if (child === null) return null;
                    return pattern.test(child) || hasMasterSwapRef(child) ? candidate : null;
                }),
        )
    ).filter((entry): entry is string => entry !== null);

    return [...new Set([...listed, ...scanned].map((entry) => path.resolve(entry)))];
}

export async function unwrapNamespace(text: string) {
    const parsed = parseIniText(text);
    parsed.sections = parsed.sections.map((section) => ({
        ...section,
        lines: unwrapSectionLines(section.lines),
    }));
    const next = serializeIni(parsed);
    if (hasCompoundMasterSwap(text) || hasMasterSwapRef(next)) {
        throw new Error("NAMESPACE_UNWRAP_INCOMPLETE");
    }
    return next;
}

const MASTER_SWAP_IF_RE =
    /^if\s+\(?\s*\$\\[^\\\s]+\\master\\swapvar\w*(?!\w)(?:\s*==\s*\S+\s*\)?)?\s*(?:;.*)?$/i;
const MASTER_SWAP_ELSE_IF_RE =
    /^(?:else\s+if|elif)\s+\(?\s*\$\\[^\\\s]+\\master\\swapvar\w*(?!\w)(?:\s*==\s*\S+\s*\)?)?\s*(?:;.*)?$/i;
const MASTER_SWAP_ELSE_RE = /^else\s*(?:;.*)?$/i;
const COMPOUND_MASTER_SWAP_RE =
    /^(?:if|else\s+if|elif)\s+\(?\s*\$\\[^\\\s]+\\master\\swapvar\w*.*(?:&&|\|\|)/i;

function unwrapSectionLines(lines: ReturnType<typeof parseIniText>["sections"][number]["lines"]) {
    const nextLines: typeof lines = [];
    let masterSwapActive = false;
    let innerIfDepth = 0;

    for (let index = 0; index < lines.length; index += 1) {
        const line = lines[index];
        const trimmed = line.raw.trim();
        const lower = trimmed.toLowerCase();

        if (
            !masterSwapActive &&
            innerIfDepth === 0 &&
            line.kind === "kv" &&
            line.key.toLowerCase() === "match_priority"
        ) {
            const upcoming = lines.slice(index + 1).find((entry) => entry.raw.trim() !== "");
            if (upcoming && MASTER_SWAP_IF_RE.test(upcoming.raw.trim())) {
                continue;
            }
        }

        if (MASTER_SWAP_IF_RE.test(trimmed)) {
            if (!masterSwapActive) {
                masterSwapActive = true;
                innerIfDepth = 0;
                continue;
            }
            innerIfDepth += 1;
            nextLines.push(unindentLine(line));
            continue;
        }

        if (
            masterSwapActive &&
            innerIfDepth === 0 &&
            (MASTER_SWAP_ELSE_IF_RE.test(trimmed) || MASTER_SWAP_ELSE_RE.test(trimmed))
        ) {
            continue;
        }

        if (lower.startsWith("if ") || lower.startsWith("if\t")) {
            if (masterSwapActive) {
                innerIfDepth += 1;
                nextLines.push(unindentLine(line));
            } else {
                nextLines.push(line);
            }
            continue;
        }

        if (lower === "endif") {
            if (masterSwapActive) {
                if (innerIfDepth > 0) {
                    innerIfDepth -= 1;
                    nextLines.push(unindentLine(line));
                } else {
                    masterSwapActive = false;
                }
            } else {
                nextLines.push(line);
            }
            continue;
        }

        if (masterSwapActive) {
            nextLines.push(unindentLine(line));
        } else {
            nextLines.push(line);
        }
    }

    return nextLines;
}

function unindentLine(line: ReturnType<typeof parseIniText>["sections"][number]["lines"][number]) {
    if (line.kind === "kv" || line.kind === "other" || line.kind === "comment") {
        const unindented = line.raw.replace(/^(?:\t| {1,4})/, "");
        return classifyLine(unindented);
    }
    return line;
}

export function wrapHashedSections(text: string, name: string, index: number) {
    const lines = text.split(/\r?\n/);
    const output: string[] = [];
    let wrapping = false;
    let pending: string[] = [];

    const flush = () => {
        if (!wrapping) return;
        const block = pending;
        pending = [];
        wrapping = false;
        output.push(...buildWrappedBlock(block, name, index));
    };

    for (const raw of lines) {
        const trimmed = raw.trim();
        const lower = trimmed.toLowerCase();
        const isComment = trimmed.startsWith(";");
        const isHeader = !isComment && trimmed.startsWith("[");
        const isHash = !isComment && (lower.startsWith("hash =") || lower.startsWith("hash="));

        if (wrapping && (isHeader || isHash)) {
            flush();
        }

        if (!wrapping && isHash) {
            output.push(raw);
            wrapping = true;
            continue;
        }

        if (wrapping) {
            if (lower.startsWith("match_priority =") || lower.startsWith("match_priority=")) {
                continue;
            }
            pending.push(raw);
            continue;
        }

        output.push(raw);
    }
    flush();
    return `${output.join("\n").replace(/\n+$/, "")}\n`;
}

function buildWrappedBlock(block: string[], name: string, baseIndex: number) {
    const vb0Indices = block.flatMap((line, idx) => {
        const classified = classifyLine(line);
        return classified.kind === "kv" && classified.key.toLowerCase() === "vb0" ? [idx] : [];
    });

    if (vb0Indices.length <= 1) {
        const head = [
            `match_priority = ${baseIndex}`,
            `if $\\${name}\\Master\\swapvar==${baseIndex}`,
        ];
        return [...head, ...closeWrap(block)];
    }

    const preamble = block.slice(0, vb0Indices[0]);
    const output = [...preamble, `match_priority = ${baseIndex}`];

    for (let b = 0; b < vb0Indices.length; b += 1) {
        const start = vb0Indices[b];
        const end = b + 1 < vb0Indices.length ? vb0Indices[b + 1] : block.length;
        const branchLines = block.slice(start, end);
        const swapIndex = baseIndex + b;
        const header =
            b === 0
                ? `if $\\${name}\\Master\\swapvar==${swapIndex}`
                : `else if $\\${name}\\Master\\swapvar==${swapIndex}`;

        output.push(header);
        if (b === vb0Indices.length - 1) {
            output.push(...closeWrap(branchLines));
            continue;
        }

        output.push(
            ...branchLines.map((line) => {
                const trimmed = line.trim();
                if (trimmed.startsWith(";") || trimmed === "" || trimmed.startsWith("[")) {
                    return line;
                }
                return `\t${line.replace(/^\t/, "")}`;
            }),
        );
    }

    return output;
}

function closeWrap(block: string[]) {
    let lastCode = -1;
    const next = block.map((line, index) => {
        const trimmed = line.trim();
        if (trimmed.startsWith(";")) return line;
        if (trimmed !== "" && !trimmed.startsWith("[")) lastCode = index;
        return trimmed === "" || trimmed.startsWith("[") ? line : `\t${line.replace(/^\t/, "")}`;
    });
    if (lastCode >= 0) {
        next.splice(lastCode + 1, 0, "endif", "");
        return next;
    }
    next.push("endif", "");
    return next;
}

function hasCompoundMasterSwap(text: string) {
    return text.split(/\r?\n/).some((line) => COMPOUND_MASTER_SWAP_RE.test(line.trim()));
}

function escapeRegExp(value: string) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
