// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Auth is the Go port of Electron src/main/services/auth.ts and backend:getStatus.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetBackendStatus(): $CancellablePromise<string> {
    return $Call.ByID(3999050796);
}

export function GetSession(): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(560344146);
}

export function HasToken(): $CancellablePromise<boolean> {
    return $Call.ByID(876115967);
}

export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1944222359);
}

export function StartLogin(): $CancellablePromise<void> {
    return $Call.ByID(1425817055);
}

export function StartLogout(): $CancellablePromise<void> {
    return $Call.ByID(4227227108);
}
