// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DriveInfo {
    "id": string;
    "rootId": string;
}

/**
 * Session matches Electron src/shared/schemas/auth.ts.
 */
export interface Session {
    "session": SessionInfo;
    "user": User;
    "drive": DriveInfo;
}

export interface SessionInfo {
    "id": string;
    "userId": string;
    "createdAt": string;
    "updatedAt": string;
    "expiresAt": string;
    "token": string;
}

export interface User {
    "id": string;
    "name": string;
    "email": string;
    "role": string;
    "image": string | null;
}
