/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Injector {
  static attach(pid: number): Injector
  /** DLL을 주입합니다. 로드된 모듈 핸들을 반환합니다. */
  inject(path: string): number
  /** 주입된 DLL을 언로드합니다. */
  uninject(handle: number): void
  /** 명시적으로 리소스를 해제합니다. (GC를 기다리지 않음) */
  detach(): void
}
