/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractArchive(archivePath: string, destinationPath: string, onProgress?: (((err: Error | null, arg: ExtractProgress) => any)) | undefined | null): Promise<string>

export interface ExtractProgress {
  percent: number
  message: string
}
