/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractArchive(archivePath: string, destinationPath: string, options?: ExtractOptions | undefined | null, onProgress?: (((err: Error | null, arg: ExtractProgress) => any)) | undefined | null): Promise<string>

export interface ExtractOptions {
  flattenSingleRoot?: boolean
}

export interface ExtractProgress {
  percent: number
  message: string
}

export declare function hasSingleTopLevelDirectory(archivePath: string): boolean
