// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EnsureSession(): $CancellablePromise<void> {
    return $Call.ByID(1682131378);
}

export function GetDownloadFilePayload(input: $models.DownloadFileInput): $CancellablePromise<$models.DownloadFilePayload> {
    return $Call.ByID(2972513600, input);
}

export function GetGameOverview(gameID: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1830677357, gameID);
}

export function GetGameSubfeed(input: $models.GameSubfeedInput): $CancellablePromise<any> {
    return $Call.ByID(3145145992, input);
}

export function GetGames(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(2572252359);
}

export function GetModCategoryOverview(input: $models.ModCategoryOverviewInput): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1231115731, input);
}

export function GetModIndex(input: $models.ModIndexInput): $CancellablePromise<any> {
    return $Call.ByID(1789862388, input);
}

export function GetModOverview(input: $models.ModOverviewInput): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2622618171, input);
}

export function GetModPosts(input: $models.ModPostsInput): $CancellablePromise<any> {
    return $Call.ByID(2079804915, input);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(4152263998);
}

export function SetManualRMCToken(input: string): $CancellablePromise<$models.ManualRMCSaveResult> {
    return $Call.ByID(3680048725, input);
}

export function ToggleModLike(input: $models.ModOverviewInput): $CancellablePromise<$models.ToggleLikeResult> {
    return $Call.ByID(747868459, input);
}
