// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DownloadFileInput {
    "itemId": number;
    "fileId": number;
    "modelName"?: string;
}

export interface DownloadFilePayload {
    "fileUrl": string;
    "title": string;
    "categoryName": string;
    "importerKey": string | null;
    "previewUrl": string | null;
    "modId": number;
    "modPageUrl": string;
    "authorName": string | null;
    "authorUrl": string | null;
    "fileMd5": string | null;
    "version": string | null;
}

export interface GameSubfeedInput {
    "gameId": number;
    "sort"?: string;
    "page"?: number;
}

export interface ManualRMCSaveResult {
    "ok": boolean;
    "errorCode"?: string;
}

export interface ModCategoryOverviewInput {
    "categoryId": number;
    "perPage"?: number;
    "page"?: number;
    "sort"?: string;
    "showEmpty"?: boolean | null;
    "modSort"?: string;
}

export interface ModIndexInput {
    "categoryId": number;
    "perPage"?: number;
    "page"?: number;
    "sort"?: string;
}

export interface ModOverviewInput {
    "itemId": number;
    "modelName"?: string;
}

export interface ModPostsInput {
    "modId": number;
    "modelName"?: string;
    "page"?: number;
    "perPage"?: number;
    "sort"?: string;
}

export interface ToggleLikeResult {
    "liked": boolean;
}
