/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class OverlayController {
  constructor()
  start(targetTitle: string, callback: ((err: Error | null, arg: NativeOverlayEvent) => any)): void
  startByPid(targetPid: number, callback: ((err: Error | null, arg: NativeOverlayEvent) => any)): void
  stop(): void
}

export interface NativeOverlayEvent {
  event: string
  rect?: WindowRect
}

export interface WindowRect {
  x: number
  y: number
  width: number
  height: number
}
