// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Data {
    xxmiPath: string | null;
    dllVersion: string | null;
    enabledImporters: EnabledImporter[] | null;
    xxmiConfig: { [_ in string]?: any } | null;
}

export interface EnabledImporter {
    key: string;
    importerFolder: string;
    packageInfo: PackageInfo;
}

export interface InstallDLLVersionInput {
    version: string;
}

export interface PackageInfo {
    latest_version: string;
    skipped_version: string;
    deployed_version: string;
    update_check_time: number;
    latest_release_notes: string;
    deployed_release_notes: string;
}
