// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function FindXXMIPath(): $CancellablePromise<string | null> {
    return $Call.ByID(2331162124);
}

export function GetEnabledImporters(): $CancellablePromise<$models.EnabledImporter[] | null> {
    return $Call.ByID(2368691442);
}

export function GetLibsReleases(): $CancellablePromise<string[] | null> {
    return $Call.ByID(902308296);
}

export function GetXXMIConfig(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1613105870);
}

export function GetXXMIData(): $CancellablePromise<$models.Data> {
    return $Call.ByID(255580904);
}

export function GetXXMIPath(): $CancellablePromise<string | null> {
    return $Call.ByID(94059527);
}

export function InstallDLLVersion(input: $models.InstallDLLVersionInput): $CancellablePromise<void> {
    return $Call.ByID(2238582977, input);
}

export function SaveXXMIPath(inputPath: string): $CancellablePromise<void> {
    return $Call.ByID(1167980486, inputPath);
}

export function StartGame(importer: string): $CancellablePromise<void> {
    return $Call.ByID(2042148136, importer);
}

export function UpdateLibsReleases(): $CancellablePromise<void> {
    return $Call.ByID(2166882569);
}
