/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface IniResult {
  name: string
  path: string
  toggleKeys: Array<ToggleKey>
  hasToggleKey: boolean
}

export declare function processIniFiles(paths: Array<string>): Array<IniResult>

export interface ToggleKey {
  sectionName: string
  iniFileName: string
  key?: string
  back?: string
  type?: string
  variable: string
  values: Array<string>
  currentValue?: string
}
