/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzePng(data: Buffer, width: number, height: number): PngAnalysis

export declare function decodeIndices(bytes: Buffer, format: string): Buffer

export interface DrawRange {
  indexCount: number
  startIndex: number
  baseVertex: number
}

export declare function ensureVec4(data: Buffer, vertexCount: number, width: number, fillW: number): Buffer

export declare function interleaveVertexBuffers(position: Buffer, positionStride: number, blend: Buffer, blendStride: number, texcoord: Buffer, texcoordStride: number): Buffer

export declare function invertRgbaAlpha(data: Buffer): Buffer

export declare function mergeDrawIndices(indices: Buffer, draws: Array<DrawRange>): MergeDrawIndicesResult

export interface MergeDrawIndicesResult {
  indices: Buffer
  invalidRanges: Array<string>
}

export declare function normalizeTangentArray(data: Buffer): Buffer

export declare function normalizeVec3Array(data: Buffer): Buffer

export declare function parseDdsSrgbState(bytes: Buffer): boolean | null

export interface PngAnalysis {
  hasAlpha: boolean
  lowRatio: number
  highRatio: number
  partialRatio: number
  lowAlphaRgbMean: number
  channelRangeMax: number
  luminanceStdDev: number
  meanR: number
  meanG: number
  meanB: number
  blueDominance: number
}

export declare function prepareTextureForMaterial(input: PrepareTextureForMaterialInput): Promise<PrepareTextureForMaterialResult>

export interface PrepareTextureForMaterialInput {
  texturePath: string
  resourceName: string
  textureFormat: string
  jpegQuality: number
  allowCacheReuse: boolean
  cacheDir: string
}

export interface PrepareTextureForMaterialResult {
  image?: Buffer
  imagePath?: string
  mimeType: string
  imageExtension: string
  usesAlpha: boolean
  invertedAlpha: boolean
  selectionScore: number
  srgbConfidence: string
  alphaMode?: string
  alphaCutoff?: number
}

export declare function readFloatAttribute(bytes: Buffer, stride: number, vertexCount: number, alignedByteOffset: number, format: string, width: number): Buffer

export declare function removeDegenerateTriangles(indices: Buffer): RemoveDegenerateTrianglesResult

export interface RemoveDegenerateTrianglesResult {
  indices: Buffer
  removed: number
}
