// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ScriptBasicRow {
    "ID": string;
    "Name": string;
    "Type": string;
    "Size": number;
}

export interface ScriptPresetItemRow {
    "PresetID": string;
    "ScriptID": string;
    "Order": number;
}

export interface ScriptPresetWithScripts {
    "ID": string;
    "Name": string;
    "Scripts": ScriptPresetItemRow[] | null;
}
