
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "util"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
lazy_static = "1.4.0"

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus"
]

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
