/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getPreviousPids(currentPid: number): Array<number>

export declare function getProcessName(pid: number): string | null

export declare function getProcessWindowState(pid: number): ProcessWindowState

export declare function getTopmostPid(pids: Array<number>): number | null

export declare const enum ProcessWindowState {
  Open = 0,
  Minimized = 1,
  NotFound = 2
}

export declare function startTracking(): void
