/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertImage(inputPath: string, options: ResizeOptions): Promise<Array<number> | null>

export interface ResizeOptions {
  width: number
  height: number
  /** png, jpeg, webp, gif, avif */
  format: string
  quality?: number
  savePath?: string
}
