// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Drive is the Wails service for Electron Drive CRUD, copy/import, and
 * transfer preparation/execution.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelCopyFromURL is Electron drive.fn.cancelCopyFromUrl.
 */
export function CancelCopyFromURL(operationID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3058829950, operationID);
}

/**
 * CopyFromURL is Electron drive.fn.copyFromUrl.
 */
export function CopyFromURL(
    params: $models.CopyFromURLParams,
): $CancellablePromise<$models.CopyFromURLResult> {
    return $Call.ByID(4154037052, params);
}

/**
 * CopyFromURLMany is Electron drive.fn.copyFromUrlMany.
 */
export function CopyFromURLMany(
    params: $models.CopyFromURLParams,
): $CancellablePromise<$models.CopyFromURLResult> {
    return $Call.ByID(3822163315, params);
}

/**
 * CopyMany is Electron drive.fn.copyMany.
 */
export function CopyMany(ids: string[] | null, destID: string): $CancellablePromise<any> {
    return $Call.ByID(704383248, ids, destID);
}

export function CreateDir(parentID: string, name: string): $CancellablePromise<any> {
    return $Call.ByID(1608070133, parentID, name);
}

export function CreateDirs(
    parentID: string,
    directories: $models.UploadDirectory[] | null,
): $CancellablePromise<$models.CreatedUploadDirectory[] | null> {
    return $Call.ByID(1760304114, parentID, directories);
}

export function DeleteItems(
    ids: string[] | null,
    action: string,
): $CancellablePromise<$models.BatchDeletionOutcome> {
    return $Call.ByID(34167167, ids, action);
}

export function GetItem(itemID: string): $CancellablePromise<any> {
    return $Call.ByID(2048674277, itemID);
}

export function GetUploadConflicts(
    params: $models.GetUploadConflictsParams,
): $CancellablePromise<$models.UploadConflictsResult> {
    return $Call.ByID(3936507094, params);
}

/**
 * ListLinkChildren is Electron drive.fn.listLinkChildren.
 */
export function ListLinkChildren(
    params: $models.ListLinkChildrenParams,
): $CancellablePromise<$models.ListChildrenResult> {
    return $Call.ByID(289936265, params);
}

/**
 * ListModChildren is Electron drive.fn.listModChildren.
 */
export function ListModChildren(
    params: $models.ListModChildrenParams,
): $CancellablePromise<$models.ListChildrenResult> {
    return $Call.ByID(554389701, params);
}

/**
 * MoveMany is Electron drive.fn.moveMany.
 */
export function MoveMany(ids: string[] | null, destID: string): $CancellablePromise<any> {
    return $Call.ByID(1111983392, ids, destID);
}

export function Rename(itemID: string, name: string): $CancellablePromise<any> {
    return $Call.ByID(2118527220, itemID, name);
}

/**
 * ResolveImportSource is Electron drive.fn.resolveImportSource.
 */
export function ResolveImportSource(
    params: $models.ResolveImportSourceParams,
): $CancellablePromise<any> {
    return $Call.ByID(158932530, params);
}

export function Search(itemID: string, params: $models.SearchParams): $CancellablePromise<any> {
    return $Call.ByID(4013868034, itemID, params);
}

export function StartDownload(
    params: $models.StartDownloadParams,
): $CancellablePromise<$models.StartDownloadResult> {
    return $Call.ByID(1135026242, params);
}

export function StartUpload(
    params: $models.StartUploadParams,
): $CancellablePromise<$models.StartUploadResult> {
    return $Call.ByID(3162032775, params);
}
